[package]
name = "migration"
version.workspace = true
edition.workspace = true

[lib]
name = "migration"
path = "src/lib.rs"

[[bin]]
name = "migration"
path = "src/main.rs"

[dependencies]
async-trait = { workspace = true }
sea-orm-migration = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
