// ============================================================
// 模型目录快照（自动生成，勿手改）
// 来源：https://pi.dev/models
// 抓取时间：2026-09-09T15:07:40.761Z · 供应商 39 / 模型 1370
// ============================================================
import type { CatalogProvider, ProviderKind } from '@/types'

export const CATALOG_SOURCE = 'https://pi.dev/models'
export const CATALOG_FETCHED_AT = '2026-09-09T15:07:40.761Z'

/** 已知供应商的默认端点与协议类型（「从目录添加」时预填；未收录者留空由用户填） */
export const PROVIDER_PRESETS: Record<string, { base_url: string; kind: ProviderKind }> = {
  "openai": { base_url: "https://api.openai.com/v1", kind: "openai" },
  "anthropic": { base_url: "https://api.anthropic.com", kind: "anthropic" },
  "deepseek": { base_url: "https://api.deepseek.com", kind: "openai-compatible" },
  "google": { base_url: "https://generativelanguage.googleapis.com/v1beta", kind: "openai-compatible" },
  "google-vertex": { base_url: "", kind: "openai-compatible" },
  "groq": { base_url: "https://api.groq.com/openai/v1", kind: "openai-compatible" },
  "mistral": { base_url: "https://api.mistral.ai/v1", kind: "openai-compatible" },
  "xai": { base_url: "https://api.x.ai/v1", kind: "openai-compatible" },
  "moonshotai": { base_url: "https://api.moonshot.ai/v1", kind: "openai-compatible" },
  "moonshotai-cn": { base_url: "https://api.moonshot.cn/v1", kind: "openai-compatible" },
  "zai": { base_url: "https://api.z.ai/api/paas/v4", kind: "openai-compatible" },
  "zai-coding-cn": { base_url: "https://open.bigmodel.cn/api/paas/v4", kind: "openai-compatible" },
  "minimax": { base_url: "https://api.minimax.chat/v1", kind: "openai-compatible" },
  "minimax-cn": { base_url: "https://api.minimaxi.com/v1", kind: "openai-compatible" },
  "together": { base_url: "https://api.together.xyz/v1", kind: "openai-compatible" },
  "cerebras": { base_url: "https://api.cerebras.ai/v1", kind: "openai-compatible" },
  "nvidia": { base_url: "https://integrate.api.nvidia.com/v1", kind: "openai-compatible" },
  "openrouter": { base_url: "https://openrouter.ai/api/v1", kind: "openai-compatible" },
  "fireworks": { base_url: "https://api.fireworks.ai/inference/v1", kind: "openai-compatible" },
  "huggingface": { base_url: "https://api-inference.huggingface.co/v1", kind: "openai-compatible" },
  "baseten": { base_url: "https://inference.baseten.co/v1", kind: "openai-compatible" },
  "cloudflare-workers-ai": { base_url: "", kind: "openai-compatible" },
  "cloudflare-ai-gateway": { base_url: "", kind: "openai-compatible" },
  "ollama": { base_url: "http://127.0.0.1:11434", kind: "ollama" },
}

export const MODEL_CATALOG: CatalogProvider[] = [
  { id: "amazon-bedrock", label: "amazon-bedrock", models: [
    { id: "au.anthropic.claude-opus-4-6-v1", name: "au anthropic claude opus 4.6" },
    { id: "au.anthropic.claude-sonnet-4-6", name: "au anthropic claude sonnet 4.6" },
    { id: "anthropic.claude-fable-5", name: "claude fable 5" },
    { id: "eu.anthropic.claude-fable-5", name: "claude fable 5 (eu)" },
    { id: "global.anthropic.claude-fable-5", name: "claude fable 5 (global)" },
    { id: "us.anthropic.claude-fable-5", name: "claude fable 5 (us)" },
    { id: "anthropic.claude-fable-5-1", name: "claude fable 5.1" },
    { id: "global.anthropic.claude-fable-5-1", name: "claude fable 5.1 (global)" },
    { id: "us.anthropic.claude-fable-5-1", name: "claude fable 5.1 (us)" },
    { id: "anthropic.claude-haiku-4-5-20251001-v1:0", name: "claude haiku 4.5" },
    { id: "au.anthropic.claude-haiku-4-5-20251001-v1:0", name: "claude haiku 4.5 (au)" },
    { id: "eu.anthropic.claude-haiku-4-5-20251001-v1:0", name: "claude haiku 4.5 (eu)" },
    { id: "global.anthropic.claude-haiku-4-5-20251001-v1:0", name: "claude haiku 4.5 (global)" },
    { id: "jp.anthropic.claude-haiku-4-5-20251001-v1:0", name: "claude haiku 4.5 (jp)" },
    { id: "us.anthropic.claude-haiku-4-5-20251001-v1:0", name: "claude haiku 4.5 (us)" },
    { id: "anthropic.claude-opus-4-1-20250805-v1:0", name: "claude opus 4.1" },
    { id: "us.anthropic.claude-opus-4-1-20250805-v1:0", name: "claude opus 4.1 (us)" },
    { id: "anthropic.claude-opus-4-5-20251101-v1:0", name: "claude opus 4.5" },
    { id: "eu.anthropic.claude-opus-4-5-20251101-v1:0", name: "claude opus 4.5 (eu)" },
    { id: "global.anthropic.claude-opus-4-5-20251101-v1:0", name: "claude opus 4.5 (global)" },
    { id: "us.anthropic.claude-opus-4-5-20251101-v1:0", name: "claude opus 4.5 (us)" },
    { id: "anthropic.claude-opus-4-6-v1", name: "claude opus 4.6" },
    { id: "eu.anthropic.claude-opus-4-6-v1", name: "claude opus 4.6 (eu)" },
    { id: "global.anthropic.claude-opus-4-6-v1", name: "claude opus 4.6 (global)" },
    { id: "us.anthropic.claude-opus-4-6-v1", name: "claude opus 4.6 (us)" },
    { id: "anthropic.claude-opus-4-7", name: "claude opus 4.7" },
    { id: "au.anthropic.claude-opus-4-7", name: "claude opus 4.7 (au)" },
    { id: "eu.anthropic.claude-opus-4-7", name: "claude opus 4.7 (eu)" },
    { id: "global.anthropic.claude-opus-4-7", name: "claude opus 4.7 (global)" },
    { id: "jp.anthropic.claude-opus-4-7", name: "claude opus 4.7 (jp)" },
    { id: "us.anthropic.claude-opus-4-7", name: "claude opus 4.7 (us)" },
    { id: "anthropic.claude-opus-4-8", name: "claude opus 4.8" },
    { id: "au.anthropic.claude-opus-4-8", name: "claude opus 4.8 (au)" },
    { id: "eu.anthropic.claude-opus-4-8", name: "claude opus 4.8 (eu)" },
    { id: "global.anthropic.claude-opus-4-8", name: "claude opus 4.8 (global)" },
    { id: "jp.anthropic.claude-opus-4-8", name: "claude opus 4.8 (jp)" },
    { id: "us.anthropic.claude-opus-4-8", name: "claude opus 4.8 (us)" },
    { id: "au.anthropic.claude-opus-5", name: "claude opus 5 (au)" },
    { id: "eu.anthropic.claude-opus-5", name: "claude opus 5 (eu)" },
    { id: "global.anthropic.claude-opus-5", name: "claude opus 5 (global)" },
    { id: "jp.anthropic.claude-opus-5", name: "claude opus 5 (jp)" },
    { id: "us.anthropic.claude-opus-5", name: "claude opus 5 (us)" },
    { id: "anthropic.claude-sonnet-4-5-20250929-v1:0", name: "claude sonnet 4.5" },
    { id: "au.anthropic.claude-sonnet-4-5-20250929-v1:0", name: "claude sonnet 4.5 (au)" },
    { id: "eu.anthropic.claude-sonnet-4-5-20250929-v1:0", name: "claude sonnet 4.5 (eu)" },
    { id: "global.anthropic.claude-sonnet-4-5-20250929-v1:0", name: "claude sonnet 4.5 (global)" },
    { id: "jp.anthropic.claude-sonnet-4-5-20250929-v1:0", name: "claude sonnet 4.5 (jp)" },
    { id: "us.anthropic.claude-sonnet-4-5-20250929-v1:0", name: "claude sonnet 4.5 (us)" },
    { id: "anthropic.claude-sonnet-4-6", name: "claude sonnet 4.6" },
    { id: "eu.anthropic.claude-sonnet-4-6", name: "claude sonnet 4.6 (eu)" },
    { id: "global.anthropic.claude-sonnet-4-6", name: "claude sonnet 4.6 (global)" },
    { id: "jp.anthropic.claude-sonnet-4-6", name: "claude sonnet 4.6 (jp)" },
    { id: "us.anthropic.claude-sonnet-4-6", name: "claude sonnet 4.6 (us)" },
    { id: "anthropic.claude-sonnet-5", name: "claude sonnet 5" },
    { id: "au.anthropic.claude-sonnet-5", name: "claude sonnet 5 (au)" },
    { id: "eu.anthropic.claude-sonnet-5", name: "claude sonnet 5 (eu)" },
    { id: "global.anthropic.claude-sonnet-5", name: "claude sonnet 5 (global)" },
    { id: "jp.anthropic.claude-sonnet-5", name: "claude sonnet 5 (jp)" },
    { id: "us.anthropic.claude-sonnet-5", name: "claude sonnet 5 (us)" },
    { id: "deepseek.r1-v1:0", name: "deepseek-r1" },
    { id: "us.deepseek.r1-v1:0", name: "deepseek-r1 (us)" },
    { id: "deepseek.v3-v1:0", name: "deepseek-v3.1" },
    { id: "deepseek.v3.2", name: "deepseek-v3.2" },
    { id: "mistral.devstral-2-123b", name: "devstral 2 123b" },
    { id: "google.gemma-3-4b-it", name: "gemma 3 4b it" },
    { id: "zai.glm-4.7", name: "glm-4.7" },
    { id: "zai.glm-4.7-flash", name: "glm-4.7-flash" },
    { id: "zai.glm-5", name: "glm-5" },
    { id: "google.gemma-3-27b-it", name: "google gemma 3 27b instruct" },
    { id: "openai.gpt-oss-safeguard-120b", name: "gpt oss safeguard 120b" },
    { id: "openai.gpt-oss-safeguard-20b", name: "gpt oss safeguard 20b" },
    { id: "openai.gpt-5.4", name: "gpt-5.4" },
    { id: "openai.gpt-5.5", name: "gpt-5.5" },
    { id: "openai.gpt-5.6-luna", name: "gpt-5.6 luna" },
    { id: "global.openai.gpt-5.6-luna", name: "gpt-5.6 luna (global)" },
    { id: "us.openai.gpt-5.6-luna", name: "gpt-5.6 luna (us)" },
    { id: "openai.gpt-5.6-sol", name: "gpt-5.6 sol" },
    { id: "global.openai.gpt-5.6-sol", name: "gpt-5.6 sol (global)" },
    { id: "us.openai.gpt-5.6-sol", name: "gpt-5.6 sol (us)" },
    { id: "openai.gpt-5.6-terra", name: "gpt-5.6 terra" },
    { id: "global.openai.gpt-5.6-terra", name: "gpt-5.6 terra (global)" },
    { id: "us.openai.gpt-5.6-terra", name: "gpt-5.6 terra (us)" },
    { id: "openai.gpt-6-astra", name: "gpt-6 astra" },
    { id: "global.openai.gpt-6-astra", name: "gpt-6 astra (global)" },
    { id: "us.openai.gpt-6-astra", name: "gpt-6 astra (us)" },
    { id: "openai.gpt-oss-120b", name: "gpt-oss-120b" },
    { id: "openai.gpt-oss-120b-1:0", name: "gpt-oss-120b" },
    { id: "openai.gpt-oss-20b", name: "gpt-oss-20b" },
    { id: "openai.gpt-oss-20b-1:0", name: "gpt-oss-20b" },
    { id: "xai.grok-4.3", name: "grok 4.3" },
    { id: "xai.grok-4.6", name: "grok 4.6" },
    { id: "global.xai.grok-4.6", name: "grok 4.6 (global)" },
    { id: "us.xai.grok-4.6", name: "grok 4.6 (us)" },
    { id: "moonshot.kimi-k2-thinking", name: "kimi k2 thinking" },
    { id: "moonshotai.kimi-k2.5", name: "kimi k2.5" },
    { id: "meta.llama3-1-70b-instruct-v1:0", name: "llama 3.1 70b instruct" },
    { id: "us.meta.llama3-1-70b-instruct-v1:0", name: "llama 3.1 70b instruct (us)" },
    { id: "meta.llama3-1-8b-instruct-v1:0", name: "llama 3.1 8b instruct" },
    { id: "us.meta.llama3-1-8b-instruct-v1:0", name: "llama 3.1 8b instruct (us)" },
    { id: "meta.llama3-3-70b-instruct-v1:0", name: "llama 3.3 70b instruct" },
    { id: "us.meta.llama3-3-70b-instruct-v1:0", name: "llama 3.3 70b instruct (us)" },
    { id: "meta.llama4-maverick-17b-instruct-v1:0", name: "llama 4 maverick 17b instruct" },
    { id: "us.meta.llama4-maverick-17b-instruct-v1:0", name: "llama 4 maverick 17b instruct (us)" },
    { id: "meta.llama4-scout-17b-instruct-v1:0", name: "llama 4 scout 17b instruct" },
    { id: "us.meta.llama4-scout-17b-instruct-v1:0", name: "llama 4 scout 17b instruct (us)" },
    { id: "mistral.magistral-small-2509", name: "magistral small 1.2" },
    { id: "minimax.minimax-m2", name: "minimax m2" },
    { id: "minimax.minimax-m2.1", name: "minimax m2.1" },
    { id: "minimax.minimax-m2.5", name: "minimax m2.5" },
    { id: "mistral.ministral-3-14b-instruct", name: "ministral 14b 3.0" },
    { id: "mistral.ministral-3-3b-instruct", name: "ministral 3 3b" },
    { id: "mistral.ministral-3-8b-instruct", name: "ministral 3 8b" },
    { id: "mistral.mistral-large-3-675b-instruct", name: "mistral large 3" },
    { id: "amazon.nova-2-lite-v1:0", name: "nova 2 lite" },
    { id: "eu.amazon.nova-2-lite-v1:0", name: "nova 2 lite (eu)" },
    { id: "global.amazon.nova-2-lite-v1:0", name: "nova 2 lite (global)" },
    { id: "jp.amazon.nova-2-lite-v1:0", name: "nova 2 lite (jp)" },
    { id: "us.amazon.nova-2-lite-v1:0", name: "nova 2 lite (us)" },
    { id: "amazon.nova-lite-v1:0", name: "nova lite" },
    { id: "apac.amazon.nova-lite-v1:0", name: "nova lite (apac)" },
    { id: "ca.amazon.nova-lite-v1:0", name: "nova lite (ca)" },
    { id: "eu.amazon.nova-lite-v1:0", name: "nova lite (eu)" },
    { id: "us.amazon.nova-lite-v1:0", name: "nova lite (us)" },
    { id: "amazon.nova-micro-v1:0", name: "nova micro" },
    { id: "apac.amazon.nova-micro-v1:0", name: "nova micro (apac)" },
    { id: "eu.amazon.nova-micro-v1:0", name: "nova micro (eu)" },
    { id: "us.amazon.nova-micro-v1:0", name: "nova micro (us)" },
    { id: "amazon.nova-pro-v1:0", name: "nova pro" },
    { id: "apac.amazon.nova-pro-v1:0", name: "nova pro (apac)" },
    { id: "eu.amazon.nova-pro-v1:0", name: "nova pro (eu)" },
    { id: "us.amazon.nova-pro-v1:0", name: "nova pro (us)" },
    { id: "nvidia.nemotron-super-3-120b", name: "nvidia nemotron 3 super 120b a12b" },
    { id: "nvidia.nemotron-nano-12b-v2", name: "nvidia nemotron nano 12b v2 vl bf16" },
    { id: "nvidia.nemotron-nano-3-30b", name: "nvidia nemotron nano 3 30b" },
    { id: "nvidia.nemotron-nano-9b-v2", name: "nvidia nemotron nano 9b v2" },
    { id: "writer.palmyra-x4-v1:0", name: "palmyra x4" },
    { id: "us.writer.palmyra-x4-v1:0", name: "palmyra x4 (us)" },
    { id: "writer.palmyra-x5-v1:0", name: "palmyra x5" },
    { id: "us.writer.palmyra-x5-v1:0", name: "palmyra x5 (us)" },
    { id: "mistral.pixtral-large-2502-v1:0", name: "pixtral large (25.02)" },
    { id: "eu.mistral.pixtral-large-2502-v1:0", name: "pixtral large (25.02) (eu)" },
    { id: "us.mistral.pixtral-large-2502-v1:0", name: "pixtral large (25.02) (us)" },
    { id: "qwen.qwen3-next-80b-a3b", name: "qwen/qwen3-next-80b-a3b-instruct" },
    { id: "qwen.qwen3-vl-235b-a22b", name: "qwen/qwen3-vl-235b-a22b-instruct" },
    { id: "qwen.qwen3-235b-a22b-2507-v1:0", name: "qwen3 235b a22b 2507" },
    { id: "qwen.qwen3-32b-v1:0", name: "qwen3 32b (dense)" },
    { id: "qwen.qwen3-coder-30b-a3b-v1:0", name: "qwen3 coder 30b a3b instruct" },
    { id: "qwen.qwen3-coder-480b-a35b-v1:0", name: "qwen3 coder 480b a35b instruct" },
    { id: "qwen.qwen3-coder-next", name: "qwen3 coder next" },
    { id: "mistral.voxtral-mini-3b-2507", name: "voxtral mini 3b 2507" },
    { id: "mistral.voxtral-small-24b-2507", name: "voxtral small 24b 2507" },
  ] },
  { id: "ant-ling", label: "ant-ling", models: [
    { id: "ling-2.6-1t", name: "ling 2.6 1t" },
    { id: "ling-2.6-flash", name: "ling 2.6 flash" },
    { id: "ring-2.6-1t", name: "ring 2.6 1t" },
  ] },
  { id: "anthropic", label: "anthropic", models: [
    { id: "claude-fable-5", name: "claude fable 5" },
    { id: "claude-fable-5-1", name: "claude fable 5.1" },
    { id: "claude-haiku-4-5-20251001", name: "claude haiku 4.5" },
    { id: "claude-haiku-4-5", name: "claude haiku 4.5 (latest)" },
    { id: "claude-opus-4-5-20251101", name: "claude opus 4.5" },
    { id: "claude-opus-4-5", name: "claude opus 4.5 (latest)" },
    { id: "claude-opus-4-6", name: "claude opus 4.6" },
    { id: "claude-opus-4-7", name: "claude opus 4.7" },
    { id: "claude-opus-4-8", name: "claude opus 4.8" },
    { id: "claude-opus-5", name: "claude opus 5" },
    { id: "claude-sonnet-4-5-20250929", name: "claude sonnet 4.5" },
    { id: "claude-sonnet-4-5", name: "claude sonnet 4.5 (latest)" },
    { id: "claude-sonnet-4-6", name: "claude sonnet 4.6" },
    { id: "claude-sonnet-5", name: "claude sonnet 5" },
  ] },
  { id: "azure-openai-responses", label: "azure-openai-responses", models: [
    { id: "gpt-4", name: "gpt-4" },
    { id: "gpt-4-turbo", name: "gpt-4 turbo" },
    { id: "gpt-4.1", name: "gpt-4.1" },
    { id: "gpt-4.1-mini", name: "gpt-4.1 mini" },
    { id: "gpt-4.1-nano", name: "gpt-4.1 nano" },
    { id: "gpt-4o", name: "gpt-4o" },
    { id: "gpt-4o-2024-05-13", name: "gpt-4o (2024-05-13)" },
    { id: "gpt-4o-2024-08-06", name: "gpt-4o (2024-08-06)" },
    { id: "gpt-4o-2024-11-20", name: "gpt-4o (2024-11-20)" },
    { id: "gpt-4o-mini", name: "gpt-4o mini" },
    { id: "gpt-5", name: "gpt-5" },
    { id: "gpt-5-chat-latest", name: "gpt-5 chat latest" },
    { id: "gpt-5-mini", name: "gpt-5 mini" },
    { id: "gpt-5-nano", name: "gpt-5 nano" },
    { id: "gpt-5-pro", name: "gpt-5 pro" },
    { id: "gpt-5.1", name: "gpt-5.1" },
    { id: "gpt-5.2", name: "gpt-5.2" },
    { id: "gpt-5.2-chat-latest", name: "gpt-5.2 chat" },
    { id: "gpt-5.2-pro", name: "gpt-5.2 pro" },
    { id: "gpt-5.3-chat-latest", name: "gpt-5.3 chat (latest)" },
    { id: "gpt-5.3-codex", name: "gpt-5.3 codex" },
    { id: "gpt-5.3-codex-spark", name: "gpt-5.3 codex spark" },
    { id: "gpt-5.4", name: "gpt-5.4" },
    { id: "gpt-5.4-mini", name: "gpt-5.4 mini" },
    { id: "gpt-5.4-nano", name: "gpt-5.4 nano" },
    { id: "gpt-5.4-pro", name: "gpt-5.4 pro" },
    { id: "gpt-5.5", name: "gpt-5.5" },
    { id: "gpt-5.5-pro", name: "gpt-5.5 pro" },
    { id: "gpt-5.6-luna", name: "gpt-5.6 luna" },
    { id: "gpt-5.6-sol", name: "gpt-5.6 sol" },
    { id: "gpt-5.6-terra", name: "gpt-5.6 terra" },
    { id: "gpt-6-astra", name: "gpt-6 astra" },
    { id: "gpt-realtime-2.1", name: "gpt-realtime-2.1" },
    { id: "o1", name: "o1" },
    { id: "o1-pro", name: "o1-pro" },
    { id: "o3", name: "o3" },
    { id: "o3-mini", name: "o3-mini" },
    { id: "o3-pro", name: "o3-pro" },
    { id: "o4-mini", name: "o4-mini" },
  ] },
  { id: "baseten", label: "baseten", models: [
    { id: "deepseek-ai/deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "deepseek-ai/deepseek-v4-pro", name: "deepseek v4 pro" },
    { id: "deepseek-ai/deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "zai-org/glm-4.7", name: "glm 4.7" },
    { id: "zai-org/glm-5", name: "glm 5" },
    { id: "zai-org/glm-5.1", name: "glm 5.1" },
    { id: "zai-org/glm-5.2", name: "glm 5.2" },
    { id: "zai-org/glm-5.2-fast", name: "glm 5.2 fast" },
    { id: "zai-org/glm-5.3", name: "glm 5.3" },
    { id: "zai-org/glm-5.3-fast", name: "glm 5.3 fast" },
    { id: "zai-org/glm-5.3-flash", name: "glm 5.3 flash" },
    { id: "thinkingmachines/inkling", name: "inkling" },
    { id: "thinkingmachines/inkling-small", name: "inkling small" },
    { id: "moonshotai/kimi-k2.5", name: "kimi k2.5" },
    { id: "moonshotai/kimi-k2.6", name: "kimi k2.6" },
    { id: "moonshotai/kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "moonshotai/kimi-k3", name: "kimi k3" },
    { id: "nvidia/nemotron-120b-a12b", name: "nemotron super" },
    { id: "nvidia/nvidia-nemotron-3-ultra-550b-a55b", name: "nemotron ultra" },
    { id: "openai/gpt-oss-120b", name: "openai gpt 120b" },
  ] },
  { id: "cerebras", label: "cerebras", models: [
    { id: "gpt-oss-120b", name: "gpt oss 120b" },
    { id: "qwen-3.8-27b", name: "qwen3.8 27b" },
  ] },
  { id: "cloudflare-ai-gateway", label: "cloudflare-ai-gateway", models: [
    { id: "claude-fable-5", name: "claude fable 5" },
    { id: "claude-fable-5.1", name: "claude fable 5.1" },
    { id: "claude-haiku-4.5", name: "claude haiku 4.5 (latest)" },
    { id: "claude-opus-4.5", name: "claude opus 4.5 (latest)" },
    { id: "claude-opus-4.6", name: "claude opus 4.6" },
    { id: "claude-opus-4.7", name: "claude opus 4.7" },
    { id: "claude-opus-4.8", name: "claude opus 4.8" },
    { id: "claude-opus-5", name: "claude opus 5" },
    { id: "claude-sonnet-4.5", name: "claude sonnet 4.5 (latest)" },
    { id: "claude-sonnet-4.6", name: "claude sonnet 4.6" },
    { id: "claude-sonnet-5", name: "claude sonnet 5" },
    { id: "workers-ai/@cf/deepseek-ai/deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "workers-ai/@cf/deepseek-ai/deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "workers-ai/@cf/google/gemma-4-26b-a4b-it", name: "gemma 4 26b a4b it" },
    { id: "workers-ai/@cf/zai-org/glm-5.2", name: "glm 5.2" },
    { id: "workers-ai/@cf/zai-org/glm-5.3", name: "glm 5.3" },
    { id: "workers-ai/@cf/zai-org/glm-5.3-flash", name: "glm 5.3 flash" },
    { id: "workers-ai/@cf/zai-org/glm-4.7-flash", name: "glm-4.7-flash" },
    { id: "workers-ai/@cf/openai/gpt-oss-120b", name: "gpt oss 120b" },
    { id: "workers-ai/@cf/openai/gpt-oss-20b", name: "gpt oss 20b" },
    { id: "gpt-4.1", name: "gpt-4.1" },
    { id: "gpt-4.1-mini", name: "gpt-4.1 mini" },
    { id: "gpt-4.1-nano", name: "gpt-4.1 nano" },
    { id: "gpt-4o", name: "gpt-4o" },
    { id: "gpt-4o-mini", name: "gpt-4o mini" },
    { id: "gpt-5", name: "gpt-5" },
    { id: "gpt-5-mini", name: "gpt-5 mini" },
    { id: "gpt-5-nano", name: "gpt-5 nano" },
    { id: "gpt-5.1", name: "gpt-5.1" },
    { id: "gpt-5.4", name: "gpt-5.4" },
    { id: "gpt-5.4-mini", name: "gpt-5.4 mini" },
    { id: "gpt-5.4-nano", name: "gpt-5.4 nano" },
    { id: "gpt-5.4-pro", name: "gpt-5.4 pro" },
    { id: "gpt-5.5", name: "gpt-5.5" },
    { id: "gpt-5.5-pro", name: "gpt-5.5 pro" },
    { id: "gpt-5.6-luna", name: "gpt-5.6 luna" },
    { id: "gpt-5.6-sol", name: "gpt-5.6 sol" },
    { id: "gpt-5.6-terra", name: "gpt-5.6 terra" },
    { id: "workers-ai/@cf/ibm-granite/granite-4.0-h-micro", name: "granite 4.0 h micro" },
    { id: "workers-ai/@cf/moonshotai/kimi-k2.6", name: "kimi k2.6" },
    { id: "workers-ai/@cf/moonshotai/kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "workers-ai/@cf/meta/llama-3.3-70b-instruct-fp8-fast", name: "llama 3.3 70b instruct fp8 fast" },
    { id: "workers-ai/@cf/meta/llama-4-scout-17b-16e-instruct", name: "llama 4 scout 17b 16e instruct" },
    { id: "workers-ai/@cf/mistralai/mistral-small-3.1-24b-instruct", name: "mistral small 3.1 24b instruct" },
    { id: "workers-ai/@cf/nvidia/nemotron-3-120b-a12b", name: "nemotron 3 super 120b" },
    { id: "o3", name: "o3" },
    { id: "o3-mini", name: "o3-mini" },
    { id: "o4-mini", name: "o4-mini" },
    { id: "workers-ai/@cf/qwen/qwen3-30b-a3b-fp8", name: "qwen3 30b a3b fp8" },
    { id: "workers-ai/@cf/qwen/qwen3.8-27b", name: "qwen3.8 27b" },
  ] },
  { id: "cloudflare-workers-ai", label: "cloudflare-workers-ai", models: [
    { id: "@cf/deepseek-ai/deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "@cf/deepseek-ai/deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "@cf/google/gemma-4-26b-a4b-it", name: "gemma 4 26b a4b it" },
    { id: "@cf/zai-org/glm-5.2", name: "glm 5.2" },
    { id: "@cf/zai-org/glm-5.3", name: "glm 5.3" },
    { id: "@cf/zai-org/glm-5.3-flash", name: "glm 5.3 flash" },
    { id: "@cf/zai-org/glm-4.7-flash", name: "glm-4.7-flash" },
    { id: "@cf/openai/gpt-oss-120b", name: "gpt oss 120b" },
    { id: "@cf/openai/gpt-oss-20b", name: "gpt oss 20b" },
    { id: "@cf/ibm-granite/granite-4.0-h-micro", name: "granite 4.0 h micro" },
    { id: "@cf/moonshotai/kimi-k2.6", name: "kimi k2.6" },
    { id: "@cf/moonshotai/kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", name: "llama 3.3 70b instruct fp8 fast" },
    { id: "@cf/meta/llama-4-scout-17b-16e-instruct", name: "llama 4 scout 17b 16e instruct" },
    { id: "@cf/mistralai/mistral-small-3.1-24b-instruct", name: "mistral small 3.1 24b instruct" },
    { id: "@cf/nvidia/nemotron-3-120b-a12b", name: "nemotron 3 super 120b" },
    { id: "@cf/qwen/qwen3-30b-a3b-fp8", name: "qwen3 30b a3b fp8" },
    { id: "@cf/qwen/qwen3.8-27b", name: "qwen3.8 27b" },
  ] },
  { id: "deepseek", label: "deepseek", models: [
    { id: "deepseek-v4-flash", name: "deepseek v4 flash" },
    { id: "deepseek-v4-flash-vision-exp", name: "deepseek v4 flash vision exp" },
    { id: "deepseek-v4-pro", name: "deepseek v4 pro" },
  ] },
  { id: "fireworks", label: "fireworks", models: [
    { id: "accounts/fireworks/models/deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "accounts/fireworks/models/deepseek-v4-flash-vision-exp", name: "deepseek v4 flash vision exp" },
    { id: "accounts/fireworks/models/deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "accounts/fireworks/models/glm-5p2", name: "glm 5.2" },
    { id: "accounts/fireworks/routers/glm-5p2-fast", name: "glm 5.2 fast" },
    { id: "accounts/fireworks/models/glm-5p3", name: "glm 5.3" },
    { id: "accounts/fireworks/routers/glm-5p3-fast", name: "glm 5.3 fast" },
    { id: "accounts/fireworks/models/glm-5p3-flash", name: "glm 5.3 flash" },
    { id: "accounts/fireworks/models/gpt-oss-120b", name: "gpt oss 120b" },
    { id: "accounts/fireworks/models/inkling", name: "inkling" },
    { id: "accounts/fireworks/models/kimi-k2p6", name: "kimi k2.6" },
    { id: "accounts/fireworks/models/kimi-k2p7-code", name: "kimi k2.7 code" },
    { id: "accounts/fireworks/models/kimi-k3", name: "kimi k3" },
    { id: "accounts/fireworks/routers/kimi-k3-fast", name: "kimi k3 fast" },
    { id: "accounts/fireworks/models/minimax-m3", name: "minimax-m3" },
    { id: "accounts/fireworks/models/muse-glimmer-30b", name: "muse glimmer 30b" },
    { id: "accounts/fireworks/models/nemotron-3-ultra-nvfp4", name: "nemotron 3 ultra 550b a55b" },
    { id: "accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b", name: "nemotron 3.5 lightning 30b a3b" },
    { id: "accounts/fireworks/models/qwen3p7-plus", name: "qwen 3.7 plus" },
    { id: "accounts/fireworks/models/qwen3p8-2p4t-a95b", name: "qwen3.8 2.4t a95b" },
    { id: "accounts/fireworks/models/qwen3p8-max", name: "qwen3.8 max" },
  ] },
  { id: "github-copilot", label: "github-copilot", models: [
    { id: "claude-fable-5", name: "claude fable 5" },
    { id: "claude-fable-5.1", name: "claude fable 5.1" },
    { id: "claude-haiku-4.5", name: "claude haiku 4.5 (latest)" },
    { id: "claude-opus-4.7", name: "claude opus 4.7" },
    { id: "claude-opus-4.8", name: "claude opus 4.8" },
    { id: "claude-opus-5", name: "claude opus 5" },
    { id: "claude-sonnet-4.6", name: "claude sonnet 4.6" },
    { id: "claude-sonnet-5", name: "claude sonnet 5" },
    { id: "gemini-3.5-flash", name: "gemini 3.5 flash" },
    { id: "gemini-3.6-flash", name: "gemini 3.6 flash" },
    { id: "gemini-3.7-flash", name: "gemini 3.7 flash" },
    { id: "gemini-3.8-flash", name: "gemini 3.8 flash" },
    { id: "gpt-5-mini", name: "gpt-5 mini" },
    { id: "gpt-5.3-codex", name: "gpt-5.3 codex" },
    { id: "gpt-5.4", name: "gpt-5.4" },
    { id: "gpt-5.4-mini", name: "gpt-5.4 mini" },
    { id: "gpt-5.4-nano", name: "gpt-5.4 nano" },
    { id: "gpt-5.5", name: "gpt-5.5" },
    { id: "gpt-5.6-luna", name: "gpt-5.6 luna" },
    { id: "gpt-5.6-sol", name: "gpt-5.6 sol" },
    { id: "gpt-5.6-terra", name: "gpt-5.6 terra" },
    { id: "gpt-6-astra", name: "gpt-6 astra" },
    { id: "grok-4.5", name: "grok 4.5" },
    { id: "grok-4.6", name: "grok 4.6" },
    { id: "kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "kimi-k3", name: "kimi k3" },
    { id: "mai-code-1-flash-picker", name: "mai-code-1-flash" },
    { id: "mai-code-1.1-flash", name: "mai-code-1.1-flash" },
  ] },
  { id: "google", label: "google", models: [
    { id: "deep-research-max-preview-04-2026", name: "deep research max preview (apr-21-2026)" },
    { id: "deep-research-preview-04-2026", name: "deep research preview (apr-21-2026)" },
    { id: "gemini-2.5-computer-use-preview-10-2025", name: "gemini 2.5 computer use preview 10-2025" },
    { id: "gemini-2.5-flash", name: "gemini 2.5 flash" },
    { id: "gemini-2.5-flash-lite", name: "gemini 2.5 flash-lite" },
    { id: "gemini-2.5-pro", name: "gemini 2.5 pro" },
    { id: "gemini-3-flash-preview", name: "gemini 3 flash preview" },
    { id: "gemini-3.1-flash-lite", name: "gemini 3.1 flash lite" },
    { id: "gemini-3.1-flash-lite-preview", name: "gemini 3.1 flash lite preview" },
    { id: "gemini-3.1-flash-live-preview", name: "gemini 3.1 flash live preview" },
    { id: "gemini-3.1-pro-preview", name: "gemini 3.1 pro preview" },
    { id: "gemini-3.1-pro-preview-customtools", name: "gemini 3.1 pro preview custom tools" },
    { id: "gemini-3.5-flash", name: "gemini 3.5 flash" },
    { id: "gemini-3.5-flash-lite", name: "gemini 3.5 flash lite" },
    { id: "gemini-3.6-flash", name: "gemini 3.6 flash" },
    { id: "gemini-3.7-flash", name: "gemini 3.7 flash" },
    { id: "gemini-3.8-flash", name: "gemini 3.8 flash" },
    { id: "gemini-flash-latest", name: "gemini flash latest" },
    { id: "gemini-flash-lite-latest", name: "gemini flash-lite latest" },
    { id: "gemma-4-26b-a4b-it", name: "gemma 4 26b a4b it" },
    { id: "gemma-4-31b-it", name: "gemma 4 31b it" },
    { id: "gemini-3.1-flash-lite-image", name: "nano banana 2 lite" },
  ] },
  { id: "google-vertex", label: "google-vertex", models: [
    { id: "gemini-2.5-flash", name: "gemini 2.5 flash" },
    { id: "gemini-2.5-flash-lite", name: "gemini 2.5 flash-lite" },
    { id: "gemini-2.5-pro", name: "gemini 2.5 pro" },
    { id: "gemini-3-flash-preview", name: "gemini 3 flash preview" },
    { id: "gemini-3.1-flash-lite", name: "gemini 3.1 flash lite" },
    { id: "gemini-3.1-pro-preview", name: "gemini 3.1 pro preview" },
    { id: "gemini-3.1-pro-preview-customtools", name: "gemini 3.1 pro preview custom tools" },
    { id: "gemini-3.5-flash", name: "gemini 3.5 flash" },
    { id: "gemini-3.5-flash-lite", name: "gemini 3.5 flash lite" },
    { id: "gemini-3.6-flash", name: "gemini 3.6 flash" },
    { id: "gemini-3.7-flash", name: "gemini 3.7 flash" },
    { id: "gemini-3.8-flash", name: "gemini 3.8 flash" },
    { id: "gemini-flash-latest", name: "gemini flash latest" },
    { id: "gemini-flash-lite-latest", name: "gemini flash-lite latest" },
  ] },
  { id: "groq", label: "groq", models: [
    { id: "openai/gpt-oss-120b", name: "gpt oss 120b" },
    { id: "openai/gpt-oss-20b", name: "gpt oss 20b" },
    { id: "llama-3.1-8b-instant", name: "llama 3.1 8b" },
    { id: "llama-3.3-70b-versatile", name: "llama 3.3 70b" },
    { id: "qwen/qwen3.6-27b", name: "qwen3.6 27b" },
    { id: "qwen/qwen3.8-27b", name: "qwen3.8 27b" },
    { id: "openai/gpt-oss-safeguard-20b", name: "safety gpt oss 20b" },
  ] },
  { id: "huggingface", label: "huggingface", models: [
    { id: "deepseek-ai/deepseek-v3-0324", name: "deepseek v3 0324" },
    { id: "deepseek-ai/deepseek-v4-flash", name: "deepseek v4 flash" },
    { id: "deepseek-ai/deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "deepseek-ai/deepseek-v4-flash-vision-exp", name: "deepseek v4 flash vision exp" },
    { id: "deepseek-ai/deepseek-v4-pro", name: "deepseek v4 pro" },
    { id: "deepseek-ai/deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "deepseek-ai/deepseek-r1", name: "deepseek-r1" },
    { id: "deepseek-ai/deepseek-r1-0528", name: "deepseek-r1-0528" },
    { id: "deepseek-ai/deepseek-v3", name: "deepseek-v3" },
    { id: "deepseek-ai/deepseek-v3.1", name: "deepseek-v3.1" },
    { id: "deepseek-ai/deepseek-v3.2", name: "deepseek-v3.2" },
    { id: "google/gemma-4-26b-a4b-it", name: "gemma 4 26b a4b it" },
    { id: "google/gemma-4-31b-it", name: "gemma 4 31b it" },
    { id: "zai-org/glm-4.5", name: "glm-4.5" },
    { id: "zai-org/glm-4.5-air", name: "glm-4.5-air" },
    { id: "zai-org/glm-4.5v", name: "glm-4.5v" },
    { id: "zai-org/glm-4.6", name: "glm-4.6" },
    { id: "zai-org/glm-4.6v-flash", name: "glm-4.6v-flash" },
    { id: "zai-org/glm-4.7", name: "glm-4.7" },
    { id: "zai-org/glm-4.7-flash", name: "glm-4.7-flash" },
    { id: "zai-org/glm-5", name: "glm-5" },
    { id: "zai-org/glm-5.1", name: "glm-5.1" },
    { id: "zai-org/glm-5.2", name: "glm-5.2" },
    { id: "zai-org/glm-5.3", name: "glm-5.3" },
    { id: "zai-org/glm-5.3-flash", name: "glm-5.3-flash" },
    { id: "openai/gpt-oss-120b", name: "gpt oss 120b" },
    { id: "openai/gpt-oss-20b", name: "gpt oss 20b" },
    { id: "tencent/hy3", name: "hy3" },
    { id: "thinkingmachines/inkling", name: "inkling" },
    { id: "thinkingmachines/inkling-small", name: "inkling small" },
    { id: "moonshotai/kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "moonshotai/kimi-k3", name: "kimi k3" },
    { id: "moonshotai/kimi-k2-instruct", name: "kimi-k2-instruct" },
    { id: "moonshotai/kimi-k2-instruct-0905", name: "kimi-k2-instruct-0905" },
    { id: "moonshotai/kimi-k2-thinking", name: "kimi-k2-thinking" },
    { id: "moonshotai/kimi-k2.5", name: "kimi-k2.5" },
    { id: "moonshotai/kimi-k2.6", name: "kimi-k2.6" },
    { id: "meta-llama/llama-3.1-8b-instruct", name: "llama-3.1-8b-instruct" },
    { id: "meta-llama/llama-3.3-70b-instruct", name: "llama-3.3-70b-instruct" },
    { id: "xiaomimimo/mimo-v2-flash", name: "mimo-v2-flash" },
    { id: "xiaomimimo/mimo-v2.5", name: "mimo-v2.5" },
    { id: "xiaomimimo/mimo-v2.5-pro", name: "mimo-v2.5-pro" },
    { id: "minimaxai/minimax-m2", name: "minimax-m2" },
    { id: "minimaxai/minimax-m2.1", name: "minimax-m2.1" },
    { id: "minimaxai/minimax-m2.5", name: "minimax-m2.5" },
    { id: "minimaxai/minimax-m2.7", name: "minimax-m2.7" },
    { id: "minimaxai/minimax-m3", name: "minimax-m3" },
    { id: "qwen/qwen2.5-coder-32b-instruct", name: "qwen2.5-coder-32b-instruct" },
    { id: "qwen/qwen3-235b-a22b", name: "qwen3 235b-a22b" },
    { id: "qwen/qwen3-235b-a22b-instruct-2507", name: "qwen3 235b-a22b instruct 2507" },
    { id: "qwen/qwen3-30b-a3b", name: "qwen3 30b a3b" },
    { id: "qwen/qwen3-32b", name: "qwen3 32b" },
    { id: "qwen/qwen3-vl-235b-a22b-instruct", name: "qwen3 vl 235b a22b instruct" },
    { id: "qwen/qwen3-vl-235b-a22b-thinking", name: "qwen3 vl 235b a22b thinking" },
    { id: "qwen/qwen3-235b-a22b-thinking-2507", name: "qwen3-235b-a22b-thinking-2507" },
    { id: "qwen/qwen3-coder-30b-a3b-instruct", name: "qwen3-coder 30b-a3b instruct" },
    { id: "qwen/qwen3-coder-480b-a35b-instruct", name: "qwen3-coder-480b-a35b-instruct" },
    { id: "qwen/qwen3-coder-next", name: "qwen3-coder-next" },
    { id: "qwen/qwen3-next-80b-a3b-instruct", name: "qwen3-next-80b-a3b-instruct" },
    { id: "qwen/qwen3-next-80b-a3b-thinking", name: "qwen3-next-80b-a3b-thinking" },
    { id: "qwen/qwen3.5-122b-a10b", name: "qwen3.5 122b-a10b" },
    { id: "qwen/qwen3.5-27b", name: "qwen3.5 27b" },
    { id: "qwen/qwen3.5-35b-a3b", name: "qwen3.5 35b-a3b" },
    { id: "qwen/qwen3.5-9b", name: "qwen3.5 9b" },
    { id: "qwen/qwen3.5-397b-a17b", name: "qwen3.5-397b-a17b" },
    { id: "qwen/qwen3.6-27b", name: "qwen3.6 27b" },
    { id: "qwen/qwen3.6-35b-a3b", name: "qwen3.6 35b-a3b" },
    { id: "qwen/qwen3.8-2.4t-a95b", name: "qwen3.8 2.4t a95b" },
    { id: "qwen/qwen3.8-27b", name: "qwen3.8 27b" },
    { id: "stepfun-ai/step-3.5-flash", name: "step 3.5 flash" },
    { id: "stepfun-ai/step-3.7-flash", name: "step 3.7 flash" },
  ] },
  { id: "kimi-coding", label: "kimi-coding", models: [
    { id: "kimi-for-coding-highspeed", name: "kimi for coding highspeed" },
    { id: "kimi-for-coding", name: "kimi k2.7 code" },
    { id: "k3", name: "kimi k3" },
    { id: "k3-256k", name: "kimi k3-256k" },
  ] },
  { id: "minimax", label: "minimax", models: [
    { id: "minimax-m2.7", name: "minimax-m2.7" },
    { id: "minimax-m2.7-highspeed", name: "minimax-m2.7-highspeed" },
    { id: "minimax-m3", name: "minimax-m3" },
  ] },
  { id: "minimax-cn", label: "minimax-cn", models: [
    { id: "minimax-m2.7", name: "minimax-m2.7" },
    { id: "minimax-m2.7-highspeed", name: "minimax-m2.7-highspeed" },
    { id: "minimax-m3", name: "minimax-m3" },
  ] },
  { id: "mistral", label: "mistral", models: [
    { id: "codestral-latest", name: "codestral (latest)" },
    { id: "devstral-2512", name: "devstral 2" },
    { id: "devstral-latest", name: "devstral 2" },
    { id: "devstral-medium-latest", name: "devstral 2 (latest)" },
    { id: "devstral-medium-2507", name: "devstral medium" },
    { id: "devstral-small-2507", name: "devstral small" },
    { id: "labs-devstral-small-2512", name: "devstral small 2" },
    { id: "devstral-small-2505", name: "devstral small 2505" },
    { id: "zai-glm-5-2", name: "glm-5.2" },
    { id: "magistral-medium-latest", name: "magistral medium (latest)" },
    { id: "magistral-small", name: "magistral small" },
    { id: "ministral-3b-latest", name: "ministral 3b (latest)" },
    { id: "ministral-8b-latest", name: "ministral 8b (latest)" },
    { id: "open-mistral-7b", name: "mistral 7b" },
    { id: "mistral-large-latest", name: "mistral large (latest)" },
    { id: "mistral-large-2411", name: "mistral large 2.1" },
    { id: "mistral-large-2512", name: "mistral large 3" },
    { id: "mistral-medium-latest", name: "mistral medium (latest)" },
    { id: "mistral-medium-2505", name: "mistral medium 3" },
    { id: "mistral-medium-2508", name: "mistral medium 3.1" },
    { id: "mistral-medium-2604", name: "mistral medium 3.5" },
    { id: "mistral-medium-3.5", name: "mistral medium 3.5" },
    { id: "mistral-nemo", name: "mistral nemo" },
    { id: "mistral-small-latest", name: "mistral small (latest)" },
    { id: "mistral-small-2506", name: "mistral small 3.2" },
    { id: "mistral-small-2603", name: "mistral small 4" },
    { id: "open-mixtral-8x22b", name: "mixtral 8x22b" },
    { id: "open-mixtral-8x7b", name: "mixtral 8x7b" },
    { id: "open-mistral-nemo", name: "open mistral nemo" },
    { id: "pixtral-12b", name: "pixtral 12b" },
    { id: "pixtral-large-latest", name: "pixtral large (latest)" },
    { id: "voxtral-small-latest", name: "voxtral small (latest)" },
  ] },
  { id: "moonshotai", label: "moonshotai", models: [
    { id: "kimi-k2.6", name: "kimi k2.6" },
    { id: "kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "kimi-k2.7-code-highspeed", name: "kimi k2.7 code highspeed" },
    { id: "kimi-k3", name: "kimi k3" },
  ] },
  { id: "moonshotai-cn", label: "moonshotai-cn", models: [
    { id: "kimi-k2.6", name: "kimi k2.6" },
    { id: "kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "kimi-k2.7-code-highspeed", name: "kimi k2.7 code highspeed" },
    { id: "kimi-k3", name: "kimi k3" },
  ] },
  { id: "nvidia", label: "nvidia", models: [
    { id: "nvidia/cosmos-reason2-8b", name: "cosmos reason2 8b" },
    { id: "deepseek-ai/deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "deepseek-ai/deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "google/gemma-3-12b-it", name: "gemma 3 12b it" },
    { id: "google/gemma-3-4b-it", name: "gemma 3 4b it" },
    { id: "openai/gpt-oss-20b", name: "gpt oss 20b" },
    { id: "moonshotai/kimi-k2.6", name: "kimi k2.6" },
    { id: "moonshotai/kimi-k3", name: "kimi k3" },
    { id: "poolside/laguna-xs-2.1", name: "laguna xs 2.1" },
    { id: "nvidia/llama-3.1-nemotron-70b-instruct", name: "llama 3.1 nemotron 70b instruct" },
    { id: "nvidia/llama-3.1-nemotron-ultra-253b-v1", name: "llama 3.1 nemotron ultra 253b" },
    { id: "meta/llama-3.2-11b-vision-instruct", name: "llama 3.2 11b vision instruct" },
    { id: "meta/llama-3.2-90b-vision-instruct", name: "llama-3.2-90b-vision-instruct" },
    { id: "mistralai/mistral-7b-instruct-v0.3", name: "mistral-7b-instruct-v0.3" },
    { id: "meta/muse-glimmer-30b", name: "muse glimmer 30b" },
    { id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning", name: "nemotron 3 nano omni" },
    { id: "nvidia/nemotron-3-super-120b-a12b", name: "nemotron 3 super" },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "nemotron 3 ultra 550b a55b" },
    { id: "nvidia/nemotron-3.5-lightning-30b-a3b", name: "nemotron 3.5 lightning 30b a3b" },
  ] },
  { id: "openai", label: "openai", models: [
    { id: "gpt-4", name: "gpt-4" },
    { id: "gpt-4-turbo", name: "gpt-4 turbo" },
    { id: "gpt-4.1", name: "gpt-4.1" },
    { id: "gpt-4.1-mini", name: "gpt-4.1 mini" },
    { id: "gpt-4.1-nano", name: "gpt-4.1 nano" },
    { id: "gpt-4o", name: "gpt-4o" },
    { id: "gpt-4o-2024-05-13", name: "gpt-4o (2024-05-13)" },
    { id: "gpt-4o-2024-08-06", name: "gpt-4o (2024-08-06)" },
    { id: "gpt-4o-2024-11-20", name: "gpt-4o (2024-11-20)" },
    { id: "gpt-4o-mini", name: "gpt-4o mini" },
    { id: "gpt-5", name: "gpt-5" },
    { id: "gpt-5-chat-latest", name: "gpt-5 chat latest" },
    { id: "gpt-5-mini", name: "gpt-5 mini" },
    { id: "gpt-5-nano", name: "gpt-5 nano" },
    { id: "gpt-5-pro", name: "gpt-5 pro" },
    { id: "gpt-5.1", name: "gpt-5.1" },
    { id: "gpt-5.2", name: "gpt-5.2" },
    { id: "gpt-5.2-chat-latest", name: "gpt-5.2 chat" },
    { id: "gpt-5.2-pro", name: "gpt-5.2 pro" },
    { id: "gpt-5.3-chat-latest", name: "gpt-5.3 chat (latest)" },
    { id: "gpt-5.3-codex", name: "gpt-5.3 codex" },
    { id: "gpt-5.3-codex-spark", name: "gpt-5.3 codex spark" },
    { id: "gpt-5.4", name: "gpt-5.4" },
    { id: "gpt-5.4-mini", name: "gpt-5.4 mini" },
    { id: "gpt-5.4-nano", name: "gpt-5.4 nano" },
    { id: "gpt-5.4-pro", name: "gpt-5.4 pro" },
    { id: "gpt-5.5", name: "gpt-5.5" },
    { id: "gpt-5.5-pro", name: "gpt-5.5 pro" },
    { id: "gpt-5.6-luna", name: "gpt-5.6 luna" },
    { id: "gpt-5.6-sol", name: "gpt-5.6 sol" },
    { id: "gpt-5.6-terra", name: "gpt-5.6 terra" },
    { id: "gpt-6-astra", name: "gpt-6 astra" },
    { id: "gpt-realtime-2.1", name: "gpt-realtime-2.1" },
    { id: "o1", name: "o1" },
    { id: "o1-pro", name: "o1-pro" },
    { id: "o3", name: "o3" },
    { id: "o3-mini", name: "o3-mini" },
    { id: "o3-pro", name: "o3-pro" },
    { id: "o4-mini", name: "o4-mini" },
  ] },
  { id: "openai-codex", label: "openai-codex", models: [
    { id: "gpt-5.3-codex-spark", name: "gpt-5.3 codex spark" },
    { id: "gpt-5.4", name: "gpt-5.4" },
    { id: "gpt-5.4-mini", name: "gpt-5.4 mini" },
    { id: "gpt-5.5", name: "gpt-5.5" },
    { id: "gpt-5.6-luna", name: "gpt-5.6 luna" },
    { id: "gpt-5.6-sol", name: "gpt-5.6 sol" },
    { id: "gpt-5.6-terra", name: "gpt-5.6 terra" },
    { id: "gpt-6-astra", name: "gpt-6 astra" },
  ] },
  { id: "opencode", label: "opencode", models: [
    { id: "big-pickle", name: "big pickle" },
    { id: "claude-fable-5", name: "claude fable 5" },
    { id: "claude-fable-5-1", name: "claude fable 5.1" },
    { id: "claude-haiku-4-5", name: "claude haiku 4.5" },
    { id: "claude-opus-4-5", name: "claude opus 4.5" },
    { id: "claude-opus-4-6", name: "claude opus 4.6" },
    { id: "claude-opus-4-7", name: "claude opus 4.7" },
    { id: "claude-opus-4-8", name: "claude opus 4.8" },
    { id: "claude-opus-5", name: "claude opus 5" },
    { id: "claude-sonnet-4", name: "claude sonnet 4" },
    { id: "claude-sonnet-4-5", name: "claude sonnet 4.5" },
    { id: "claude-sonnet-4-6", name: "claude sonnet 4.6" },
    { id: "claude-sonnet-5", name: "claude sonnet 5" },
    { id: "deepseek-v4-flash", name: "deepseek v4 flash" },
    { id: "deepseek-v4-flash-vision-exp", name: "deepseek v4 flash vision exp" },
    { id: "deepseek-v4-pro", name: "deepseek v4 pro" },
    { id: "gemini-3-flash", name: "gemini 3 flash" },
    { id: "gemini-3.1-pro", name: "gemini 3.1 pro preview" },
    { id: "gemini-3.5-flash", name: "gemini 3.5 flash" },
    { id: "gemini-3.5-flash-lite", name: "gemini 3.5 flash lite" },
    { id: "gemini-3.6-flash", name: "gemini 3.6 flash" },
    { id: "gemini-3.7-flash", name: "gemini 3.7 flash" },
    { id: "gemini-3.8-flash", name: "gemini 3.8 flash" },
    { id: "glm-5", name: "glm-5" },
    { id: "glm-5.1", name: "glm-5.1" },
    { id: "glm-5.2", name: "glm-5.2" },
    { id: "glm-5.3", name: "glm-5.3" },
    { id: "glm-5.3-flash", name: "glm-5.3-flash" },
    { id: "gpt-5", name: "gpt-5" },
    { id: "gpt-5-codex", name: "gpt-5 codex" },
    { id: "gpt-5-nano", name: "gpt-5 nano" },
    { id: "gpt-5.1", name: "gpt-5.1" },
    { id: "gpt-5.1-codex", name: "gpt-5.1 codex" },
    { id: "gpt-5.1-codex-max", name: "gpt-5.1 codex max" },
    { id: "gpt-5.1-codex-mini", name: "gpt-5.1 codex mini" },
    { id: "gpt-5.2", name: "gpt-5.2" },
    { id: "gpt-5.2-codex", name: "gpt-5.2 codex" },
    { id: "gpt-5.3-codex", name: "gpt-5.3 codex" },
    { id: "gpt-5.4", name: "gpt-5.4" },
    { id: "gpt-5.4-mini", name: "gpt-5.4 mini" },
    { id: "gpt-5.4-nano", name: "gpt-5.4 nano" },
    { id: "gpt-5.4-pro", name: "gpt-5.4 pro" },
    { id: "gpt-5.5", name: "gpt-5.5" },
    { id: "gpt-5.5-pro", name: "gpt-5.5 pro" },
    { id: "gpt-5.6-luna", name: "gpt-5.6 luna" },
    { id: "gpt-5.6-sol", name: "gpt-5.6 sol (50% off)" },
    { id: "gpt-5.6-terra", name: "gpt-5.6 terra" },
    { id: "gpt-6-astra", name: "gpt-6 astra" },
    { id: "grok-4.5", name: "grok 4.5" },
    { id: "grok-4.6", name: "grok 4.6" },
    { id: "grok-build-0.1", name: "grok build 0.1" },
    { id: "kimi-k2.5", name: "kimi k2.5" },
    { id: "kimi-k2.6", name: "kimi k2.6" },
    { id: "kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "kimi-k3", name: "kimi k3" },
    { id: "ling-3.0-flash-fin-free", name: "ling 3.0 flash fin free" },
    { id: "mimo-v2.5-free", name: "mimo v2.5 free" },
    { id: "minimax-m2.5", name: "minimax-m2.5" },
    { id: "minimax-m2.7", name: "minimax-m2.7" },
    { id: "minimax-m3", name: "minimax-m3" },
    { id: "muse-spark-1.2", name: "muse spark 1.2" },
    { id: "muse-spark-1.2-contributor-free", name: "muse spark 1.2 free" },
    { id: "muse-spark-1.3", name: "muse spark 1.3" },
    { id: "muse-spark-1.3-contributor-free", name: "muse spark 1.3 free" },
    { id: "nemotron-3-ultra-free", name: "nemotron 3 ultra free" },
    { id: "nemotron-3.5-lightning-free", name: "nemotron 3.5 lightning free" },
    { id: "qwen3.5-plus", name: "qwen3.5 plus" },
    { id: "qwen3.6-plus", name: "qwen3.6 plus" },
  ] },
  { id: "opencode-go", label: "opencode-go", models: [
    { id: "deepseek-v4-flash", name: "deepseek v4 flash" },
    { id: "deepseek-v4-flash-vision-exp", name: "deepseek v4 flash vision exp" },
    { id: "deepseek-v4-pro", name: "deepseek v4 pro (new)" },
    { id: "glm-5.1", name: "glm-5.1" },
    { id: "glm-5.2", name: "glm-5.2" },
    { id: "glm-5.3", name: "glm-5.3" },
    { id: "glm-5.3-flash", name: "glm-5.3-flash (2x usage)" },
    { id: "gpt-5.6-luna", name: "gpt-5.6 luna" },
    { id: "grok-4.6", name: "grok 4.6" },
    { id: "hy3", name: "hy3" },
    { id: "hy4-preview", name: "hy4 preview" },
    { id: "kimi-k2.6", name: "kimi k2.6" },
    { id: "kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "kimi-k3", name: "kimi k3" },
    { id: "longcat-2.0", name: "longcat-2.0" },
    { id: "mimo-v2.5", name: "mimo v2.5" },
    { id: "mimo-v2.5-pro", name: "mimo v2.5 pro" },
    { id: "minimax-m2.7", name: "minimax-m2.7" },
    { id: "minimax-m3", name: "minimax-m3" },
    { id: "muse-spark-1.2-contributor", name: "muse spark 1.2 contributor" },
    { id: "muse-spark-1.3-contributor", name: "muse spark 1.3 contributor" },
    { id: "omen-alpha", name: "omen alpha" },
    { id: "qwen3.6-plus", name: "qwen3.6 plus" },
    { id: "qwen3.7-max", name: "qwen3.7 max" },
    { id: "qwen3.7-plus", name: "qwen3.7 plus" },
    { id: "qwen3.8-flash", name: "qwen3.8 flash" },
    { id: "qwen3.8-max", name: "qwen3.8 max" },
  ] },
  { id: "openrouter", label: "openrouter", models: [
    { id: "aion-labs/aion-2.0", name: "aionlabs: aion-2.0" },
    { id: "aion-labs/aion-3.0", name: "aionlabs: aion-3.0" },
    { id: "aion-labs/aion-3.0-mini", name: "aionlabs: aion-3.0-mini" },
    { id: "amazon/nova-2-lite-v1", name: "amazon: nova 2 lite" },
    { id: "amazon/nova-lite-v1", name: "amazon: nova lite 1.0" },
    { id: "amazon/nova-micro-v1", name: "amazon: nova micro 1.0" },
    { id: "amazon/nova-premier-v1", name: "amazon: nova premier 1.0" },
    { id: "amazon/nova-pro-v1", name: "amazon: nova pro 1.0" },
    { id: "~anthropic/claude-haiku-latest", name: "anthropic claude haiku latest" },
    { id: "~anthropic/claude-sonnet-latest", name: "anthropic claude sonnet latest" },
    { id: "anthropic/claude-3-haiku", name: "anthropic: claude 3 haiku" },
    { id: "anthropic/claude-fable-5", name: "anthropic: claude fable 5" },
    { id: "anthropic/claude-fable-5:batch", name: "anthropic: claude fable 5 (batch)" },
    { id: "anthropic/claude-fable-5.1", name: "anthropic: claude fable 5.1" },
    { id: "anthropic/claude-fable-5.1:batch", name: "anthropic: claude fable 5.1 (batch)" },
    { id: "~anthropic/claude-fable-latest", name: "anthropic: claude fable latest" },
    { id: "anthropic/claude-haiku-4.5", name: "anthropic: claude haiku 4.5" },
    { id: "anthropic/claude-haiku-4.5:batch", name: "anthropic: claude haiku 4.5 (batch)" },
    { id: "anthropic/claude-opus-4", name: "anthropic: claude opus 4" },
    { id: "anthropic/claude-opus-4.1", name: "anthropic: claude opus 4.1" },
    { id: "anthropic/claude-opus-4.1:batch", name: "anthropic: claude opus 4.1 (batch)" },
    { id: "anthropic/claude-opus-4.5", name: "anthropic: claude opus 4.5" },
    { id: "anthropic/claude-opus-4.5:batch", name: "anthropic: claude opus 4.5 (batch)" },
    { id: "anthropic/claude-opus-4.6", name: "anthropic: claude opus 4.6" },
    { id: "anthropic/claude-opus-4.6:batch", name: "anthropic: claude opus 4.6 (batch)" },
    { id: "anthropic/claude-opus-4.7", name: "anthropic: claude opus 4.7" },
    { id: "anthropic/claude-opus-4.7:batch", name: "anthropic: claude opus 4.7 (batch)" },
    { id: "anthropic/claude-opus-4.8", name: "anthropic: claude opus 4.8" },
    { id: "anthropic/claude-opus-4.8:batch", name: "anthropic: claude opus 4.8 (batch)" },
    { id: "~anthropic/claude-opus-latest", name: "anthropic: claude opus latest" },
    { id: "anthropic/claude-sonnet-4", name: "anthropic: claude sonnet 4" },
    { id: "anthropic/claude-sonnet-4.5", name: "anthropic: claude sonnet 4.5" },
    { id: "anthropic/claude-sonnet-4.5:batch", name: "anthropic: claude sonnet 4.5 (batch)" },
    { id: "anthropic/claude-sonnet-4.6", name: "anthropic: claude sonnet 4.6" },
    { id: "anthropic/claude-sonnet-4.6:batch", name: "anthropic: claude sonnet 4.6 (batch)" },
    { id: "anthropic/claude-sonnet-5", name: "anthropic: claude sonnet 5" },
    { id: "anthropic/claude-sonnet-5:batch", name: "anthropic: claude sonnet 5 (batch)" },
    { id: "arcee-ai/trinity-large-thinking", name: "arcee ai: trinity large thinking" },
    { id: "auto", name: "auto" },
    { id: "openrouter/auto", name: "auto router" },
    { id: "openrouter/auto-beta", name: "auto router (beta)" },
    { id: "bytedance-seed/seed-1.6", name: "bytedance seed: seed 1.6" },
    { id: "bytedance-seed/seed-1.6-flash", name: "bytedance seed: seed 1.6 flash" },
    { id: "bytedance-seed/seed-2-1-turbo", name: "bytedance seed: seed 2.1 turbo" },
    { id: "bytedance-seed/seed-2.0-code", name: "bytedance seed: seed-2.0-code" },
    { id: "bytedance-seed/seed-2.0-lite", name: "bytedance seed: seed-2.0-lite" },
    { id: "bytedance-seed/seed-2.0-mini", name: "bytedance seed: seed-2.0-mini" },
    { id: "anthropic/claude-opus-5", name: "claude opus 5" },
    { id: "anthropic/claude-opus-5:batch", name: "claude opus 5 (batch)" },
    { id: "cohere/command-r-08-2024", name: "cohere: command r (08-2024)" },
    { id: "cohere/command-r-plus-08-2024", name: "cohere: command r+ (08-2024)" },
    { id: "cohere/north-mini-code:free", name: "cohere: north mini code (free)" },
    { id: "~deepseek/deepseek-v4-flash-latest", name: "deepseek v4 flash latest" },
    { id: "deepseek/deepseek-chat", name: "deepseek: deepseek v3" },
    { id: "deepseek/deepseek-chat-v3-0324", name: "deepseek: deepseek v3 0324" },
    { id: "deepseek/deepseek-chat-v3.1", name: "deepseek: deepseek v3.1" },
    { id: "deepseek/deepseek-v3.1-terminus", name: "deepseek: deepseek v3.1 terminus" },
    { id: "deepseek/deepseek-v3.2", name: "deepseek: deepseek v3.2" },
    { id: "deepseek/deepseek-v3.2-exp", name: "deepseek: deepseek v3.2 exp" },
    { id: "deepseek/deepseek-v4-flash", name: "deepseek: deepseek v4 flash 0423" },
    { id: "deepseek/deepseek-v4-flash-0731", name: "deepseek: deepseek v4 flash 0731" },
    { id: "deepseek/deepseek-v4-flash-0731:batch", name: "deepseek: deepseek v4 flash 0731 (batch)" },
    { id: "deepseek/deepseek-v4-flash-vision-exp", name: "deepseek: deepseek v4 flash vision exp" },
    { id: "deepseek/deepseek-v4-flash-vision-exp:batch", name: "deepseek: deepseek v4 flash vision exp (batch)" },
    { id: "deepseek/deepseek-v4-pro", name: "deepseek: deepseek v4 pro 0423" },
    { id: "deepseek/deepseek-v4-pro-0813", name: "deepseek: deepseek v4 pro 0813" },
    { id: "deepseek/deepseek-v4-pro-0813:batch", name: "deepseek: deepseek v4 pro 0813 (batch)" },
    { id: "deepseek/deepseek-r1", name: "deepseek: r1" },
    { id: "deepseek/deepseek-r1-0528", name: "deepseek: r1 0528" },
    { id: "dots-studio/dots-3-note-preview:free", name: "dots studio: dots3-note preview (free)" },
    { id: "openrouter/free", name: "free models router" },
    { id: "~google/gemini-flash-latest", name: "google gemini flash latest" },
    { id: "~google/gemini-pro-latest", name: "google gemini pro latest" },
    { id: "google/gemini-2.5-flash", name: "google: gemini 2.5 flash" },
    { id: "google/gemini-2.5-flash:batch", name: "google: gemini 2.5 flash (batch)" },
    { id: "google/gemini-2.5-flash-lite", name: "google: gemini 2.5 flash lite" },
    { id: "google/gemini-2.5-flash-lite:batch", name: "google: gemini 2.5 flash lite (batch)" },
    { id: "google/gemini-2.5-pro", name: "google: gemini 2.5 pro" },
    { id: "google/gemini-2.5-pro:batch", name: "google: gemini 2.5 pro (batch)" },
    { id: "google/gemini-2.5-pro-preview-05-06", name: "google: gemini 2.5 pro preview 05-06" },
    { id: "google/gemini-2.5-pro-preview", name: "google: gemini 2.5 pro preview 06-05" },
    { id: "google/gemini-3-flash-preview", name: "google: gemini 3 flash preview" },
    { id: "google/gemini-3-flash-preview:batch", name: "google: gemini 3 flash preview (batch)" },
    { id: "google/gemini-3.1-flash-lite", name: "google: gemini 3.1 flash lite" },
    { id: "google/gemini-3.1-flash-lite:batch", name: "google: gemini 3.1 flash lite (batch)" },
    { id: "google/gemini-3.1-flash-lite-preview", name: "google: gemini 3.1 flash lite preview" },
    { id: "google/gemini-3.1-pro-preview", name: "google: gemini 3.1 pro preview" },
    { id: "google/gemini-3.1-pro-preview:batch", name: "google: gemini 3.1 pro preview (batch)" },
    { id: "google/gemini-3.1-pro-preview-customtools", name: "google: gemini 3.1 pro preview custom tools" },
    { id: "google/gemini-3.5-flash", name: "google: gemini 3.5 flash" },
    { id: "google/gemini-3.5-flash:batch", name: "google: gemini 3.5 flash (batch)" },
    { id: "google/gemini-3.5-flash-lite", name: "google: gemini 3.5 flash lite" },
    { id: "google/gemini-3.5-flash-lite:batch", name: "google: gemini 3.5 flash lite (batch)" },
    { id: "google/gemini-3.6-flash", name: "google: gemini 3.6 flash" },
    { id: "google/gemini-3.6-flash:batch", name: "google: gemini 3.6 flash (batch)" },
    { id: "google/gemini-3.7-flash", name: "google: gemini 3.7 flash" },
    { id: "google/gemini-3.7-flash:batch", name: "google: gemini 3.7 flash (batch)" },
    { id: "google/gemini-3.8-flash", name: "google: gemini 3.8 flash" },
    { id: "google/gemini-3.8-flash:batch", name: "google: gemini 3.8 flash (batch)" },
    { id: "google/gemma-3-12b-it", name: "google: gemma 3 12b" },
    { id: "google/gemma-3-27b-it", name: "google: gemma 3 27b" },
    { id: "google/gemma-4-26b-a4b-it", name: "google: gemma 4 26b a4b " },
    { id: "google/gemma-4-26b-a4b-it:free", name: "google: gemma 4 26b a4b  (free)" },
    { id: "google/gemma-4-31b-it", name: "google: gemma 4 31b" },
    { id: "google/gemma-4-31b-it:batch", name: "google: gemma 4 31b (batch)" },
    { id: "google/gemma-4-31b-it:free", name: "google: gemma 4 31b (free)" },
    { id: "google/gemini-3-pro-image", name: "google: nano banana pro (gemini 3 pro image)" },
    { id: "ibm-granite/granite-4.2-8b", name: "ibm: granite 4.2 8b" },
    { id: "inception/mercury-2", name: "inception: mercury 2" },
    { id: "inception/mercury-2.5", name: "inception: mercury 2.5" },
    { id: "inclusionai/ling-3.0-flash", name: "inclusionai: ling 3.0 flash" },
    { id: "inclusionai/ling-3.0-flash-fin", name: "inclusionai: ling 3.0 flash fin" },
    { id: "inclusionai/ling-3.0-flash-fin:free", name: "inclusionai: ling 3.0 flash fin (free)" },
    { id: "inclusionai/ling-3.0-flash-sante:free", name: "inclusionai: ling 3.0 flash sante (free)" },
    { id: "kwaipilot/kat-coder-pro-v2", name: "kwaipilot: kat-coder-pro v2" },
    { id: "kwaipilot/kat-coder-pro-v2.5", name: "kwaipilot: kat-coder-pro v2.5" },
    { id: "liquid/lfm-2.5-2.6b:free", name: "liquidai: lfm2.5-2.6b (free)" },
    { id: "meituan/longcat-2.0", name: "meituan: longcat 2.0" },
    { id: "meta-llama/llama-3.1-70b-instruct", name: "meta: llama 3.1 70b instruct" },
    { id: "meta-llama/llama-3.1-8b-instruct", name: "meta: llama 3.1 8b instruct" },
    { id: "meta-llama/llama-3.3-70b-instruct", name: "meta: llama 3.3 70b instruct" },
    { id: "meta-llama/llama-4-maverick", name: "meta: llama 4 maverick" },
    { id: "meta-llama/llama-4-scout", name: "meta: llama 4 scout" },
    { id: "meta/muse-glimmer-30b", name: "meta: muse glimmer 30b" },
    { id: "meta/muse-glimmer-30b:batch", name: "meta: muse glimmer 30b (batch)" },
    { id: "meta/muse-spark-1.1", name: "meta: muse spark 1.1" },
    { id: "meta/muse-spark-1.2", name: "meta: muse spark 1.2" },
    { id: "meta/muse-spark-1.2-contributor", name: "meta: muse spark 1.2 contributor" },
    { id: "meta/muse-spark-1.3", name: "meta: muse spark 1.3" },
    { id: "meta/muse-spark-1.3-contributor", name: "meta: muse spark 1.3 contributor" },
    { id: "minimax/minimax-m1", name: "minimax: minimax m1" },
    { id: "minimax/minimax-m2", name: "minimax: minimax m2" },
    { id: "minimax/minimax-m2.1", name: "minimax: minimax m2.1" },
    { id: "minimax/minimax-m2.5", name: "minimax: minimax m2.5" },
    { id: "minimax/minimax-m2.7", name: "minimax: minimax m2.7" },
    { id: "minimax/minimax-m3", name: "minimax: minimax m3" },
    { id: "minimax/minimax-m3:batch", name: "minimax: minimax m3 (batch)" },
    { id: "mistralai/mistral-large", name: "mistral large" },
    { id: "mistralai/mistral-large-2407", name: "mistral large 2407" },
    { id: "mistralai/codestral-2508", name: "mistral: codestral 2508" },
    { id: "mistralai/devstral-2512", name: "mistral: devstral 2 2512" },
    { id: "mistralai/ministral-14b-2512", name: "mistral: ministral 3 14b 2512" },
    { id: "mistralai/ministral-3b-2512", name: "mistral: ministral 3 3b 2512" },
    { id: "mistralai/ministral-8b-2512", name: "mistral: ministral 3 8b 2512" },
    { id: "mistralai/mistral-large-2512", name: "mistral: mistral large 3 2512" },
    { id: "mistralai/mistral-medium-3", name: "mistral: mistral medium 3" },
    { id: "mistralai/mistral-medium-3.1", name: "mistral: mistral medium 3.1" },
    { id: "mistralai/mistral-medium-3-5", name: "mistral: mistral medium 3.5" },
    { id: "mistralai/mistral-medium-3-5:batch", name: "mistral: mistral medium 3.5 (batch)" },
    { id: "mistralai/mistral-nemo", name: "mistral: mistral nemo" },
    { id: "mistralai/mistral-small-3.2-24b-instruct", name: "mistral: mistral small 3.2 24b" },
    { id: "mistralai/mistral-small-2603", name: "mistral: mistral small 4" },
    { id: "mistralai/mixtral-8x22b-instruct", name: "mistral: mixtral 8x22b instruct" },
    { id: "mistralai/mistral-saba", name: "mistral: saba" },
    { id: "mistralai/voxtral-small-24b-2507", name: "mistral: voxtral small 24b 2507" },
    { id: "~moonshotai/kimi-latest", name: "moonshotai kimi latest" },
    { id: "moonshotai/kimi-k2", name: "moonshotai: kimi k2 0711" },
    { id: "moonshotai/kimi-k2-0905", name: "moonshotai: kimi k2 0905" },
    { id: "moonshotai/kimi-k2-thinking", name: "moonshotai: kimi k2 thinking" },
    { id: "moonshotai/kimi-k2.5", name: "moonshotai: kimi k2.5" },
    { id: "moonshotai/kimi-k2.6", name: "moonshotai: kimi k2.6" },
    { id: "moonshotai/kimi-k2.7-code", name: "moonshotai: kimi k2.7 code" },
    { id: "moonshotai/kimi-k3", name: "moonshotai: kimi k3" },
    { id: "moonshotai/kimi-k3:batch", name: "moonshotai: kimi k3 (batch)" },
    { id: "nex-agi/nex-n2.5-mini:free", name: "nex agi: nex-n2.5-mini (free)" },
    { id: "nex-agi/nex-n2.5-pro:free", name: "nex agi: nex-n2.5-pro (free)" },
    { id: "nvidia/nemotron-3-nano-30b-a3b", name: "nvidia: nemotron 3 nano 30b a3b" },
    { id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", name: "nvidia: nemotron 3 nano omni (free)" },
    { id: "nvidia/nemotron-3-super-120b-a12b", name: "nvidia: nemotron 3 super" },
    { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "nvidia: nemotron 3 super (free)" },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "nvidia: nemotron 3 ultra" },
    { id: "nvidia/nemotron-3-ultra-550b-a55b:free", name: "nvidia: nemotron 3 ultra (free)" },
    { id: "nvidia/nemotron-3.5-lightning", name: "nvidia: nemotron 3.5 lightning" },
    { id: "nvidia/nemotron-3.5-lightning:free", name: "nvidia: nemotron 3.5 lightning (free)" },
    { id: "~openai/gpt-latest", name: "openai gpt latest" },
    { id: "~openai/gpt-mini-latest", name: "openai gpt mini latest" },
    { id: "openai/gpt-audio", name: "openai: gpt audio" },
    { id: "openai/gpt-audio-mini", name: "openai: gpt audio mini" },
    { id: "openai/gpt-chat-latest", name: "openai: gpt chat latest" },
    { id: "openai/gpt-3.5-turbo", name: "openai: gpt-3.5 turbo" },
    { id: "openai/gpt-3.5-turbo:batch", name: "openai: gpt-3.5 turbo (batch)" },
    { id: "openai/gpt-3.5-turbo-0613", name: "openai: gpt-3.5 turbo (older v0613)" },
    { id: "openai/gpt-3.5-turbo-16k", name: "openai: gpt-3.5 turbo 16k" },
    { id: "openai/gpt-4", name: "openai: gpt-4" },
    { id: "openai/gpt-4-turbo", name: "openai: gpt-4 turbo" },
    { id: "openai/gpt-4-turbo:batch", name: "openai: gpt-4 turbo (batch)" },
    { id: "openai/gpt-4-turbo-preview", name: "openai: gpt-4 turbo preview" },
    { id: "openai/gpt-4.1", name: "openai: gpt-4.1" },
    { id: "openai/gpt-4.1:batch", name: "openai: gpt-4.1 (batch)" },
    { id: "openai/gpt-4.1-mini", name: "openai: gpt-4.1 mini" },
    { id: "openai/gpt-4.1-mini:batch", name: "openai: gpt-4.1 mini (batch)" },
    { id: "openai/gpt-4.1-nano", name: "openai: gpt-4.1 nano" },
    { id: "openai/gpt-4.1-nano:batch", name: "openai: gpt-4.1 nano (batch)" },
    { id: "openai/gpt-4o", name: "openai: gpt-4o" },
    { id: "openai/gpt-4o-2024-05-13", name: "openai: gpt-4o (2024-05-13)" },
    { id: "openai/gpt-4o-2024-08-06", name: "openai: gpt-4o (2024-08-06)" },
    { id: "openai/gpt-4o-2024-11-20", name: "openai: gpt-4o (2024-11-20)" },
    { id: "openai/gpt-4o:batch", name: "openai: gpt-4o (batch)" },
    { id: "openai/gpt-4o-mini", name: "openai: gpt-4o-mini" },
    { id: "openai/gpt-4o-mini-2024-07-18", name: "openai: gpt-4o-mini (2024-07-18)" },
    { id: "openai/gpt-4o-mini:batch", name: "openai: gpt-4o-mini (batch)" },
    { id: "openai/gpt-5", name: "openai: gpt-5" },
    { id: "openai/gpt-5:batch", name: "openai: gpt-5 (batch)" },
    { id: "openai/gpt-5-mini", name: "openai: gpt-5 mini" },
    { id: "openai/gpt-5-mini:batch", name: "openai: gpt-5 mini (batch)" },
    { id: "openai/gpt-5-nano", name: "openai: gpt-5 nano" },
    { id: "openai/gpt-5-nano:batch", name: "openai: gpt-5 nano (batch)" },
    { id: "openai/gpt-5-pro", name: "openai: gpt-5 pro" },
    { id: "openai/gpt-5-pro:batch", name: "openai: gpt-5 pro (batch)" },
    { id: "openai/gpt-5.1", name: "openai: gpt-5.1" },
    { id: "openai/gpt-5.1:batch", name: "openai: gpt-5.1 (batch)" },
    { id: "openai/gpt-5.1-codex", name: "openai: gpt-5.1-codex" },
    { id: "openai/gpt-5.1-codex-max", name: "openai: gpt-5.1-codex-max" },
    { id: "openai/gpt-5.1-codex-mini", name: "openai: gpt-5.1-codex-mini" },
    { id: "openai/gpt-5.2", name: "openai: gpt-5.2" },
    { id: "openai/gpt-5.2:batch", name: "openai: gpt-5.2 (batch)" },
    { id: "openai/gpt-5.2-chat", name: "openai: gpt-5.2 chat" },
    { id: "openai/gpt-5.2-pro", name: "openai: gpt-5.2 pro" },
    { id: "openai/gpt-5.2-pro:batch", name: "openai: gpt-5.2 pro (batch)" },
    { id: "openai/gpt-5.2-codex", name: "openai: gpt-5.2-codex" },
    { id: "openai/gpt-5.3-codex", name: "openai: gpt-5.3-codex" },
    { id: "openai/gpt-5.4", name: "openai: gpt-5.4" },
    { id: "openai/gpt-5.4:batch", name: "openai: gpt-5.4 (batch)" },
    { id: "openai/gpt-5.4-mini", name: "openai: gpt-5.4 mini" },
    { id: "openai/gpt-5.4-mini:batch", name: "openai: gpt-5.4 mini (batch)" },
    { id: "openai/gpt-5.4-nano", name: "openai: gpt-5.4 nano" },
    { id: "openai/gpt-5.4-nano:batch", name: "openai: gpt-5.4 nano (batch)" },
    { id: "openai/gpt-5.4-pro", name: "openai: gpt-5.4 pro" },
    { id: "openai/gpt-5.4-pro:batch", name: "openai: gpt-5.4 pro (batch)" },
    { id: "openai/gpt-5.5", name: "openai: gpt-5.5" },
    { id: "openai/gpt-5.5:batch", name: "openai: gpt-5.5 (batch)" },
    { id: "openai/gpt-5.5-pro", name: "openai: gpt-5.5 pro" },
    { id: "openai/gpt-5.5-pro:batch", name: "openai: gpt-5.5 pro (batch)" },
    { id: "openai/gpt-5.6-luna", name: "openai: gpt-5.6 luna" },
    { id: "openai/gpt-5.6-luna:batch", name: "openai: gpt-5.6 luna (batch)" },
    { id: "openai/gpt-5.6-luna-pro", name: "openai: gpt-5.6 luna pro" },
    { id: "openai/gpt-5.6-luna-pro:batch", name: "openai: gpt-5.6 luna pro (batch)" },
    { id: "openai/gpt-5.6-sol", name: "openai: gpt-5.6 sol" },
    { id: "openai/gpt-5.6-sol:batch", name: "openai: gpt-5.6 sol (batch)" },
    { id: "openai/gpt-5.6-sol-pro", name: "openai: gpt-5.6 sol pro" },
    { id: "openai/gpt-5.6-sol-pro:batch", name: "openai: gpt-5.6 sol pro (batch)" },
    { id: "openai/gpt-5.6-terra", name: "openai: gpt-5.6 terra" },
    { id: "openai/gpt-5.6-terra:batch", name: "openai: gpt-5.6 terra (batch)" },
    { id: "openai/gpt-5.6-terra-pro", name: "openai: gpt-5.6 terra pro" },
    { id: "openai/gpt-5.6-terra-pro:batch", name: "openai: gpt-5.6 terra pro (batch)" },
    { id: "openai/gpt-6-astra", name: "openai: gpt-6 astra" },
    { id: "openai/gpt-6-astra:batch", name: "openai: gpt-6 astra (batch)" },
    { id: "openai/gpt-6-astra-pro", name: "openai: gpt-6 astra pro" },
    { id: "openai/gpt-6-astra-pro:batch", name: "openai: gpt-6 astra pro (batch)" },
    { id: "openai/gpt-oss-120b", name: "openai: gpt-oss-120b" },
    { id: "openai/gpt-oss-120b:batch", name: "openai: gpt-oss-120b (batch)" },
    { id: "openai/gpt-oss-20b", name: "openai: gpt-oss-20b" },
    { id: "openai/gpt-oss-safeguard-20b", name: "openai: gpt-oss-safeguard-20b" },
    { id: "openai/o1", name: "openai: o1" },
    { id: "openai/o3", name: "openai: o3" },
    { id: "openai/o3:batch", name: "openai: o3 (batch)" },
    { id: "openai/o3-mini", name: "openai: o3 mini" },
    { id: "openai/o3-mini:batch", name: "openai: o3 mini (batch)" },
    { id: "openai/o3-mini-high", name: "openai: o3 mini high" },
    { id: "openai/o3-pro", name: "openai: o3 pro" },
    { id: "openai/o4-mini", name: "openai: o4 mini" },
    { id: "openai/o4-mini:batch", name: "openai: o4 mini (batch)" },
    { id: "openai/o4-mini-high", name: "openai: o4 mini high" },
    { id: "openrouter/fusion", name: "openrouter: fusion" },
    { id: "poolside/laguna-s-2.1", name: "poolside: laguna s 2.1" },
    { id: "poolside/laguna-s-2.1:free", name: "poolside: laguna s 2.1 (free)" },
    { id: "poolside/laguna-xs-2.1", name: "poolside: laguna xs 2.1" },
    { id: "poolside/laguna-xs-2.1:free", name: "poolside: laguna xs 2.1 (free)" },
    { id: "qwen/qwen-plus-2025-07-28", name: "qwen: qwen plus 0728" },
    { id: "qwen/qwen-plus", name: "qwen: qwen-plus" },
    { id: "qwen/qwen-2.5-7b-instruct", name: "qwen: qwen2.5 7b instruct" },
    { id: "qwen/qwen3-14b", name: "qwen: qwen3 14b" },
    { id: "qwen/qwen3-235b-a22b", name: "qwen: qwen3 235b a22b" },
    { id: "qwen/qwen3-235b-a22b-2507", name: "qwen: qwen3 235b a22b instruct 2507" },
    { id: "qwen/qwen3-235b-a22b-thinking-2507", name: "qwen: qwen3 235b a22b thinking 2507" },
    { id: "qwen/qwen3-30b-a3b", name: "qwen: qwen3 30b a3b" },
    { id: "qwen/qwen3-30b-a3b-instruct-2507", name: "qwen: qwen3 30b a3b instruct 2507" },
    { id: "qwen/qwen3-30b-a3b-thinking-2507", name: "qwen: qwen3 30b a3b thinking 2507" },
    { id: "qwen/qwen3-32b", name: "qwen: qwen3 32b" },
    { id: "qwen/qwen3-8b", name: "qwen: qwen3 8b" },
    { id: "qwen/qwen3-coder-30b-a3b-instruct", name: "qwen: qwen3 coder 30b a3b instruct" },
    { id: "qwen/qwen3-coder", name: "qwen: qwen3 coder 480b a35b" },
    { id: "qwen/qwen3-coder-flash", name: "qwen: qwen3 coder flash" },
    { id: "qwen/qwen3-coder-next", name: "qwen: qwen3 coder next" },
    { id: "qwen/qwen3-coder-plus", name: "qwen: qwen3 coder plus" },
    { id: "qwen/qwen3-max", name: "qwen: qwen3 max" },
    { id: "qwen/qwen3-max-thinking", name: "qwen: qwen3 max thinking" },
    { id: "qwen/qwen3-next-80b-a3b-instruct", name: "qwen: qwen3 next 80b a3b instruct" },
    { id: "qwen/qwen3-next-80b-a3b-thinking", name: "qwen: qwen3 next 80b a3b thinking" },
    { id: "qwen/qwen3-vl-235b-a22b-instruct", name: "qwen: qwen3 vl 235b a22b instruct" },
    { id: "qwen/qwen3-vl-235b-a22b-thinking", name: "qwen: qwen3 vl 235b a22b thinking" },
    { id: "qwen/qwen3-vl-30b-a3b-instruct", name: "qwen: qwen3 vl 30b a3b instruct" },
    { id: "qwen/qwen3-vl-30b-a3b-thinking", name: "qwen: qwen3 vl 30b a3b thinking" },
    { id: "qwen/qwen3-vl-32b-instruct", name: "qwen: qwen3 vl 32b instruct" },
    { id: "qwen/qwen3-vl-8b-instruct", name: "qwen: qwen3 vl 8b instruct" },
    { id: "qwen/qwen3-vl-8b-thinking", name: "qwen: qwen3 vl 8b thinking" },
    { id: "qwen/qwen3.5-397b-a17b", name: "qwen: qwen3.5 397b a17b" },
    { id: "qwen/qwen3.5-plus-02-15", name: "qwen: qwen3.5 plus 2026-02-15" },
    { id: "qwen/qwen3.5-plus-20260420", name: "qwen: qwen3.5 plus 2026-04-20" },
    { id: "qwen/qwen3.5-122b-a10b", name: "qwen: qwen3.5-122b-a10b" },
    { id: "qwen/qwen3.5-27b", name: "qwen: qwen3.5-27b" },
    { id: "qwen/qwen3.5-35b-a3b", name: "qwen: qwen3.5-35b-a3b" },
    { id: "qwen/qwen3.5-9b", name: "qwen: qwen3.5-9b" },
    { id: "qwen/qwen3.5-9b:batch", name: "qwen: qwen3.5-9b (batch)" },
    { id: "qwen/qwen3.5-flash-02-23", name: "qwen: qwen3.5-flash" },
    { id: "qwen/qwen3.6-27b", name: "qwen: qwen3.6 27b" },
    { id: "qwen/qwen3.6-35b-a3b", name: "qwen: qwen3.6 35b a3b" },
    { id: "qwen/qwen3.6-flash", name: "qwen: qwen3.6 flash" },
    { id: "qwen/qwen3.6-max-preview", name: "qwen: qwen3.6 max preview" },
    { id: "qwen/qwen3.6-plus", name: "qwen: qwen3.6 plus" },
    { id: "qwen/qwen3.7-flash", name: "qwen: qwen3.7 flash" },
    { id: "qwen/qwen3.7-max", name: "qwen: qwen3.7 max" },
    { id: "qwen/qwen3.7-plus", name: "qwen: qwen3.7 plus" },
    { id: "qwen/qwen3.8-2.4t-a95b", name: "qwen: qwen3.8 2.4t a95b" },
    { id: "qwen/qwen3.8-2.4t-a95b:batch", name: "qwen: qwen3.8 2.4t a95b (batch)" },
    { id: "qwen/qwen3.8-27b", name: "qwen: qwen3.8 27b" },
    { id: "qwen/qwen3.8-flash", name: "qwen: qwen3.8 flash" },
    { id: "qwen/qwen3.8-max-0902", name: "qwen: qwen3.8 max (0902)" },
    { id: "qwen/qwen-2.5-72b-instruct", name: "qwen2.5 72b instruct" },
    { id: "rekaai/reka-edge", name: "reka edge" },
    { id: "relace/relace-search", name: "relace: relace search" },
    { id: "sakana/fugu-ultra", name: "sakana: fugu ultra" },
    { id: "sakana/sakana-namazu", name: "sakana: sakana namazu" },
    { id: "sao10k/l3.1-euryale-70b", name: "sao10k: llama 3.1 euryale 70b v2.2" },
    { id: "x-ai/grok-4.20", name: "spacexai: grok 4.20" },
    { id: "x-ai/grok-4.3", name: "spacexai: grok 4.3" },
    { id: "x-ai/grok-4.3:batch", name: "spacexai: grok 4.3 (batch)" },
    { id: "x-ai/grok-4.5", name: "spacexai: grok 4.5" },
    { id: "x-ai/grok-4.6", name: "spacexai: grok 4.6" },
    { id: "x-ai/grok-build-0.1", name: "spacexai: grok build 0.1" },
    { id: "stepfun/step-3.5-flash", name: "stepfun: step 3.5 flash" },
    { id: "stepfun/step-3.7-flash", name: "stepfun: step 3.7 flash" },
    { id: "tencent/hy3", name: "tencent: hy3" },
    { id: "tencent/hy3-preview", name: "tencent: hy3 preview" },
    { id: "tencent/hy4-preview", name: "tencent: hy4 preview" },
    { id: "thedrummer/unslopnemo-12b", name: "thedrummer: unslopnemo 12b" },
    { id: "thinkingmachines/inkling", name: "thinking machines: inkling" },
    { id: "thinkingmachines/inkling:batch", name: "thinking machines: inkling (batch)" },
    { id: "thinkingmachines/inkling:free", name: "thinking machines: inkling (free)" },
    { id: "thinkingmachines/inkling-small", name: "thinking machines: inkling small" },
    { id: "thinkingmachines/inkling-small:batch", name: "thinking machines: inkling small (batch)" },
    { id: "thinkingmachines/inkling-small:free", name: "thinking machines: inkling small (free)" },
    { id: "upstage/solar-pro-3", name: "upstage: solar pro 3" },
    { id: "upstage/solar-pro4", name: "upstage: solar pro 4" },
    { id: "~x-ai/grok-latest", name: "xai: grok latest" },
    { id: "xiaomi/mimo-v2.5", name: "xiaomi: mimo-v2.5" },
    { id: "xiaomi/mimo-v2.5-pro", name: "xiaomi: mimo-v2.5-pro" },
    { id: "z-ai/glm-4.5", name: "z.ai: glm 4.5" },
    { id: "z-ai/glm-4.5-air", name: "z.ai: glm 4.5 air" },
    { id: "z-ai/glm-4.5v", name: "z.ai: glm 4.5v" },
    { id: "z-ai/glm-4.6", name: "z.ai: glm 4.6" },
    { id: "z-ai/glm-4.6v", name: "z.ai: glm 4.6v" },
    { id: "z-ai/glm-4.7", name: "z.ai: glm 4.7" },
    { id: "z-ai/glm-4.7-flash", name: "z.ai: glm 4.7 flash" },
    { id: "z-ai/glm-5", name: "z.ai: glm 5" },
    { id: "z-ai/glm-5-turbo", name: "z.ai: glm 5 turbo" },
    { id: "z-ai/glm-5.1", name: "z.ai: glm 5.1" },
    { id: "z-ai/glm-5.2", name: "z.ai: glm 5.2" },
    { id: "z-ai/glm-5.2:batch", name: "z.ai: glm 5.2 (batch)" },
    { id: "z-ai/glm-5.3", name: "z.ai: glm 5.3" },
    { id: "z-ai/glm-5.3:batch", name: "z.ai: glm 5.3 (batch)" },
    { id: "z-ai/glm-5.3-flash", name: "z.ai: glm 5.3 flash" },
    { id: "z-ai/glm-5.3-flash:batch", name: "z.ai: glm 5.3 flash (batch)" },
    { id: "z-ai/glm-5v-turbo", name: "z.ai: glm 5v turbo" },
    { id: "~z-ai/glm-flash-latest", name: "z.ai: glm flash latest" },
    { id: "~z-ai/glm-latest", name: "z.ai: glm latest" },
  ] },
  { id: "qwen-token-plan", label: "qwen-token-plan", models: [
    { id: "deepseek-v3.2", name: "deepseek v3.2" },
    { id: "deepseek-v4-flash", name: "deepseek v4 flash" },
    { id: "deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "deepseek-v4-pro", name: "deepseek v4 pro" },
    { id: "deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "glm-5", name: "glm-5" },
    { id: "glm-5.1", name: "glm-5.1" },
    { id: "glm-5.2", name: "glm-5.2" },
    { id: "kimi-k2.5", name: "kimi k2.5" },
    { id: "kimi-k2.6", name: "kimi k2.6" },
    { id: "kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "minimax-m2.5", name: "minimax-m2.5" },
    { id: "qwen3.6-flash", name: "qwen3.6 flash" },
    { id: "qwen3.6-plus", name: "qwen3.6 plus" },
    { id: "qwen3.7-max", name: "qwen3.7 max" },
    { id: "qwen3.7-plus", name: "qwen3.7 plus" },
    { id: "qwen3.8-flash", name: "qwen3.8 flash" },
    { id: "qwen3.8-max", name: "qwen3.8 max" },
  ] },
  { id: "qwen-token-plan-cn", label: "qwen-token-plan-cn", models: [
    { id: "deepseek-v3.2", name: "deepseek v3.2" },
    { id: "deepseek-v4-flash", name: "deepseek v4 flash" },
    { id: "deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "deepseek-v4-pro", name: "deepseek v4 pro" },
    { id: "deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "glm-5", name: "glm-5" },
    { id: "glm-5.1", name: "glm-5.1" },
    { id: "glm-5.2", name: "glm-5.2" },
    { id: "kimi-k2.5", name: "kimi k2.5" },
    { id: "kimi-k2.6", name: "kimi k2.6" },
    { id: "kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "minimax-m2.5", name: "minimax-m2.5" },
    { id: "qwen3.6-flash", name: "qwen3.6 flash" },
    { id: "qwen3.6-plus", name: "qwen3.6 plus" },
    { id: "qwen3.7-max", name: "qwen3.7 max" },
    { id: "qwen3.7-plus", name: "qwen3.7 plus" },
    { id: "qwen3.8-flash", name: "qwen3.8 flash" },
    { id: "qwen3.8-max", name: "qwen3.8 max" },
  ] },
  { id: "qwen-token-plan-individual", label: "qwen-token-plan-individual", models: [
    { id: "deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "deepseek-v4-pro", name: "deepseek v4 pro" },
    { id: "deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "glm-5.2", name: "glm-5.2" },
    { id: "qwen3.6-flash", name: "qwen3.6 flash" },
    { id: "qwen3.7-max", name: "qwen3.7 max" },
    { id: "qwen3.7-plus", name: "qwen3.7 plus" },
    { id: "qwen3.8-flash", name: "qwen3.8 flash" },
    { id: "qwen3.8-max", name: "qwen3.8 max" },
  ] },
  { id: "together", label: "together", models: [
    { id: "deepseek-ai/deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "deepseek-ai/deepseek-v4-pro", name: "deepseek v4 pro" },
    { id: "deepseek-ai/deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "google/gemma-4-31b-it", name: "gemma 4 31b instruct" },
    { id: "zai-org/glm-5.2", name: "glm-5.2" },
    { id: "zai-org/glm-5.3", name: "glm-5.3" },
    { id: "zai-org/glm-5.3-flash", name: "glm-5.3-flash" },
    { id: "openai/gpt-oss-120b", name: "gpt oss 120b" },
    { id: "openai/gpt-oss-20b", name: "gpt oss 20b" },
    { id: "thinkingmachines/inkling", name: "inkling" },
    { id: "moonshotai/kimi-k2.6", name: "kimi k2.6" },
    { id: "moonshotai/kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "moonshotai/kimi-k3", name: "kimi k3" },
    { id: "meta-llama/llama-3.3-70b-instruct-turbo", name: "llama 3.3 70b" },
    { id: "minimaxai/minimax-m2.7", name: "minimax-m2.7" },
    { id: "minimaxai/minimax-m3", name: "minimax-m3" },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "nemotron 3 ultra 550b a55b" },
    { id: "qwen/qwen2.5-7b-instruct-turbo", name: "qwen 2.5 7b instruct turbo" },
    { id: "qwen/qwen3.5-9b", name: "qwen3.5 9b" },
    { id: "qwen/qwen3.6-plus", name: "qwen3.6 plus" },
    { id: "qwen/qwen3.7-max", name: "qwen3.7 max" },
  ] },
  { id: "vercel-ai-gateway", label: "vercel-ai-gateway", models: [
    { id: "bytedance/seed-1.8", name: "bytedance seed 1.8" },
    { id: "anthropic/claude-3-haiku", name: "claude 3 haiku" },
    { id: "anthropic/claude-fable-5", name: "claude fable 5" },
    { id: "anthropic/claude-fable-5.1", name: "claude fable 5.1" },
    { id: "anthropic/claude-haiku-4.5", name: "claude haiku 4.5" },
    { id: "anthropic/claude-opus-4", name: "claude opus 4" },
    { id: "anthropic/claude-opus-4.5", name: "claude opus 4.5" },
    { id: "anthropic/claude-opus-4.6", name: "claude opus 4.6" },
    { id: "anthropic/claude-opus-4.7", name: "claude opus 4.7" },
    { id: "anthropic/claude-opus-4.8", name: "claude opus 4.8" },
    { id: "anthropic/claude-opus-4.8-fast", name: "claude opus 4.8 (fast)" },
    { id: "anthropic/claude-opus-5", name: "claude opus 5" },
    { id: "anthropic/claude-opus-5-fast", name: "claude opus 5 (fast)" },
    { id: "anthropic/claude-sonnet-4", name: "claude sonnet 4" },
    { id: "anthropic/claude-sonnet-4.5", name: "claude sonnet 4.5" },
    { id: "anthropic/claude-sonnet-4.6", name: "claude sonnet 4.6" },
    { id: "anthropic/claude-sonnet-5", name: "claude sonnet 5" },
    { id: "cohere/command-a", name: "command a" },
    { id: "deepseek/deepseek-v3.1", name: "deepseek v3.1" },
    { id: "deepseek/deepseek-v3.1-terminus", name: "deepseek v3.1 terminus" },
    { id: "deepseek/deepseek-v3.2", name: "deepseek v3.2" },
    { id: "deepseek/deepseek-v3.2-thinking", name: "deepseek v3.2 thinking" },
    { id: "deepseek/deepseek-v4-flash", name: "deepseek v4 flash" },
    { id: "deepseek/deepseek-v4-flash-0731", name: "deepseek v4 flash 0731" },
    { id: "deepseek/deepseek-v4-flash-vision-exp", name: "deepseek v4 flash vision exp" },
    { id: "deepseek/deepseek-v4-pro", name: "deepseek v4 pro" },
    { id: "deepseek/deepseek-v4-pro-0813", name: "deepseek v4 pro 0813" },
    { id: "deepseek/deepseek-v4.1-flash-beta", name: "deepseek v4.1 flash beta" },
    { id: "deepseek/deepseek-r1", name: "deepseek-r1" },
    { id: "mistral/devstral-2", name: "devstral 2" },
    { id: "mistral/devstral-small-2", name: "devstral small 2" },
    { id: "sakana/fugu-ultra", name: "fugu ultra" },
    { id: "google/gemini-2.5-flash", name: "gemini 2.5 flash" },
    { id: "google/gemini-2.5-flash-lite", name: "gemini 2.5 flash lite" },
    { id: "google/gemini-2.5-pro", name: "gemini 2.5 pro" },
    { id: "google/gemini-3-flash", name: "gemini 3 flash" },
    { id: "google/gemini-3.1-flash-lite", name: "gemini 3.1 flash lite" },
    { id: "google/gemini-3.1-pro-preview", name: "gemini 3.1 pro preview" },
    { id: "google/gemini-3.5-flash", name: "gemini 3.5 flash" },
    { id: "google/gemini-3.5-flash-lite", name: "gemini 3.5 flash lite" },
    { id: "google/gemini-3.6-flash", name: "gemini 3.6 flash" },
    { id: "google/gemini-3.7-flash", name: "gemini 3.7 flash" },
    { id: "google/gemini-3.8-flash", name: "gemini 3.8 flash" },
    { id: "google/gemma-4-31b-it", name: "gemma 4 31b it" },
    { id: "zai/glm-4.5", name: "glm 4.5" },
    { id: "zai/glm-4.5-air", name: "glm 4.5 air" },
    { id: "zai/glm-4.5v", name: "glm 4.5v" },
    { id: "zai/glm-4.6", name: "glm 4.6" },
    { id: "zai/glm-4.7", name: "glm 4.7" },
    { id: "zai/glm-4.7-flash", name: "glm 4.7 flash" },
    { id: "zai/glm-4.7-flashx", name: "glm 4.7 flashx" },
    { id: "zai/glm-5", name: "glm 5" },
    { id: "zai/glm-5-turbo", name: "glm 5 turbo" },
    { id: "zai/glm-5.1", name: "glm 5.1" },
    { id: "zai/glm-5.2", name: "glm 5.2" },
    { id: "zai/glm-5.2-fast", name: "glm 5.2 fast" },
    { id: "zai/glm-5.3", name: "glm 5.3" },
    { id: "zai/glm-5.3-fast", name: "glm 5.3 fast" },
    { id: "zai/glm-5.3-flash", name: "glm 5.3 flash" },
    { id: "zai/glm-5v-turbo", name: "glm 5v turbo" },
    { id: "google/gemma-4-26b-a4b-it", name: "google gemma 4 26b a4b" },
    { id: "openai/gpt-5.1-codex-max", name: "gpt 5.1 codex max" },
    { id: "openai/gpt-5.1-codex-mini", name: "gpt 5.1 codex mini" },
    { id: "openai/gpt-5.1-thinking", name: "gpt 5.1 thinking" },
    { id: "openai/gpt-5.1-thinking-fast", name: "gpt 5.1 thinking (fast)" },
    { id: "openai/gpt-5.2", name: "gpt 5.2" },
    { id: "openai/gpt-5.2-pro", name: "gpt 5.2 " },
    { id: "openai/gpt-5.2-fast", name: "gpt 5.2 (fast)" },
    { id: "openai/gpt-5.2-codex", name: "gpt 5.2 codex" },
    { id: "openai/gpt-5.3-codex", name: "gpt 5.3 codex" },
    { id: "openai/gpt-5.3-codex-fast", name: "gpt 5.3 codex (fast)" },
    { id: "openai/gpt-5.4", name: "gpt 5.4" },
    { id: "openai/gpt-5.4-fast", name: "gpt 5.4 (fast)" },
    { id: "openai/gpt-5.4-mini", name: "gpt 5.4 mini" },
    { id: "openai/gpt-5.4-mini-fast", name: "gpt 5.4 mini (fast)" },
    { id: "openai/gpt-5.4-nano", name: "gpt 5.4 nano" },
    { id: "openai/gpt-5.4-pro", name: "gpt 5.4 pro" },
    { id: "openai/gpt-5.5", name: "gpt 5.5" },
    { id: "openai/gpt-5.5-fast", name: "gpt 5.5 (fast)" },
    { id: "openai/gpt-5.5-pro", name: "gpt 5.5 pro" },
    { id: "openai/gpt-5.6-luna", name: "gpt 5.6 luna" },
    { id: "openai/gpt-5.6-luna-fast", name: "gpt 5.6 luna (fast)" },
    { id: "openai/gpt-5.6-sol", name: "gpt 5.6 sol" },
    { id: "openai/gpt-5.6-sol-fast", name: "gpt 5.6 sol (fast)" },
    { id: "openai/gpt-5.6-terra", name: "gpt 5.6 terra" },
    { id: "openai/gpt-5.6-terra-fast", name: "gpt 5.6 terra (fast)" },
    { id: "openai/gpt-oss-120b", name: "gpt oss 120b" },
    { id: "openai/gpt-oss-20b", name: "gpt oss 20b" },
    { id: "openai/gpt-oss-safeguard-120b", name: "gpt oss safeguard 120b" },
    { id: "openai/gpt-oss-safeguard-20b", name: "gpt oss safeguard 20b" },
    { id: "openai/gpt-3.5-turbo", name: "gpt-3.5 turbo" },
    { id: "openai/gpt-4-turbo", name: "gpt-4 turbo" },
    { id: "openai/gpt-4.1", name: "gpt-4.1" },
    { id: "openai/gpt-4.1-fast", name: "gpt-4.1 (fast)" },
    { id: "openai/gpt-4.1-mini", name: "gpt-4.1 mini" },
    { id: "openai/gpt-4.1-mini-fast", name: "gpt-4.1 mini (fast)" },
    { id: "openai/gpt-4.1-nano", name: "gpt-4.1 nano" },
    { id: "openai/gpt-4.1-nano-fast", name: "gpt-4.1 nano (fast)" },
    { id: "openai/gpt-4o", name: "gpt-4o" },
    { id: "openai/gpt-4o-fast", name: "gpt-4o (fast)" },
    { id: "openai/gpt-4o-mini", name: "gpt-4o mini" },
    { id: "openai/gpt-4o-mini-fast", name: "gpt-4o mini (fast)" },
    { id: "openai/gpt-5", name: "gpt-5" },
    { id: "openai/gpt-5-fast", name: "gpt-5 (fast)" },
    { id: "openai/gpt-5-mini", name: "gpt-5 mini" },
    { id: "openai/gpt-5-mini-fast", name: "gpt-5 mini (fast)" },
    { id: "openai/gpt-5-nano", name: "gpt-5 nano" },
    { id: "openai/gpt-5-pro", name: "gpt-5 pro" },
    { id: "openai/gpt-5-codex", name: "gpt-5-codex" },
    { id: "openai/gpt-5.1-codex", name: "gpt-5.1-codex" },
    { id: "openai/gpt-6-astra", name: "gpt-6 astra" },
    { id: "openai/gpt-6-astra-fast", name: "gpt-6 astra (fast)" },
    { id: "spacexai/grok-4.1-fast-non-reasoning", name: "grok 4.1 fast non-reasoning" },
    { id: "spacexai/grok-4.1-fast-reasoning", name: "grok 4.1 fast reasoning" },
    { id: "spacexai/grok-4.20-non-reasoning-beta", name: "grok 4.20 beta non-reasoning" },
    { id: "spacexai/grok-4.20-reasoning-beta", name: "grok 4.20 beta reasoning" },
    { id: "spacexai/grok-4.20-multi-agent-beta", name: "grok 4.20 multi agent beta" },
    { id: "spacexai/grok-4.20-multi-agent", name: "grok 4.20 multi-agent" },
    { id: "spacexai/grok-4.20-non-reasoning", name: "grok 4.20 non-reasoning" },
    { id: "spacexai/grok-4.20-reasoning", name: "grok 4.20 reasoning" },
    { id: "spacexai/grok-4.3", name: "grok 4.3" },
    { id: "spacexai/grok-4.5", name: "grok 4.5" },
    { id: "spacexai/grok-4.6", name: "grok 4.6" },
    { id: "spacexai/grok-build-0.1", name: "grok build 0.1" },
    { id: "tencent/hy3", name: "hy3" },
    { id: "thinkingmachines/inkling", name: "inkling" },
    { id: "thinkingmachines/inkling-small", name: "inkling small" },
    { id: "interfaze/interfaze-beta", name: "interfaze beta" },
    { id: "kwaipilot/kat-coder-air-v2.5", name: "kat coder air v2.5" },
    { id: "kwaipilot/kat-coder-pro-v2", name: "kat coder pro v2" },
    { id: "kwaipilot/kat-coder-pro-v2.5", name: "kat coder pro v2.5" },
    { id: "kwaipilot/kat-coder-pro-v1", name: "kat-coder-pro v1" },
    { id: "moonshotai/kimi-k2", name: "kimi k2 instruct" },
    { id: "moonshotai/kimi-k2-thinking", name: "kimi k2 thinking" },
    { id: "moonshotai/kimi-k2.5", name: "kimi k2.5" },
    { id: "moonshotai/kimi-k2.6", name: "kimi k2.6" },
    { id: "moonshotai/kimi-k2.7-code", name: "kimi k2.7 code" },
    { id: "moonshotai/kimi-k2.7-code-highspeed", name: "kimi k2.7 code high speed" },
    { id: "moonshotai/kimi-k3", name: "kimi k3" },
    { id: "moonshotai/kimi-k3-fast", name: "kimi k3 fast" },
    { id: "poolside/laguna-s-2.1", name: "laguna s 2.1" },
    { id: "poolside/laguna-s-2.1-free", name: "laguna s 2.1 free" },
    { id: "inclusionai/ling-3.0-flash", name: "ling 3.0 flash" },
    { id: "inclusionai/ling-3.0-flash-fin", name: "ling 3.0 flash fin" },
    { id: "inclusionai/ling-3.0-flash-fin-free", name: "ling 3.0 flash fin (free)" },
    { id: "inclusionai/ling-3.0-flash-sante", name: "ling 3.0 flash sante" },
    { id: "inclusionai/ling-3.0-flash-sante-free", name: "ling 3.0 flash sante (free)" },
    { id: "meta/llama-3.1-70b", name: "llama 3.1 70b instruct" },
    { id: "meta/llama-3.1-8b", name: "llama 3.1 8b instruct" },
    { id: "meta/llama-3.3-70b", name: "llama 3.3 70b instruct" },
    { id: "meta/llama-4-maverick", name: "llama 4 maverick 17b instruct" },
    { id: "meta/llama-4-scout", name: "llama 4 scout 17b instruct" },
    { id: "inception/mercury-2", name: "mercury 2" },
    { id: "inception/mercury-2.5", name: "mercury 2.5" },
    { id: "inception/mercury-coder-small", name: "mercury coder small beta" },
    { id: "xiaomi/mimo-v2.5", name: "mimo m2.5" },
    { id: "xiaomi/mimo-v2.5-pro", name: "mimo v2.5 pro" },
    { id: "minimax/minimax-m2", name: "minimax m2" },
    { id: "minimax/minimax-m2.1", name: "minimax m2.1" },
    { id: "minimax/minimax-m2.1-lightning", name: "minimax m2.1 lightning" },
    { id: "minimax/minimax-m2.5", name: "minimax m2.5" },
    { id: "minimax/minimax-m2.5-highspeed", name: "minimax m2.5 high speed" },
    { id: "minimax/minimax-m2.7", name: "minimax m2.7" },
    { id: "minimax/minimax-m2.7-highspeed", name: "minimax m2.7 high speed" },
    { id: "minimax/minimax-m3", name: "minimax m3" },
    { id: "mistral/ministral-14b", name: "ministral 14b" },
    { id: "mistral/ministral-3b", name: "ministral 3b" },
    { id: "mistral/ministral-8b", name: "ministral 8b" },
    { id: "mistral/codestral", name: "mistral codestral" },
    { id: "mistral/mistral-large-3", name: "mistral large 3" },
    { id: "mistral/mistral-medium", name: "mistral medium 3.1" },
    { id: "mistral/mistral-medium-3.5", name: "mistral medium latest" },
    { id: "mistral/mistral-nemo", name: "mistral nemo 12b" },
    { id: "mistral/mistral-small", name: "mistral small" },
    { id: "meta/muse-glimmer-30b", name: "muse glimmer 30b" },
    { id: "meta/muse-spark-1.1", name: "muse spark 1.1" },
    { id: "meta/muse-spark-1.2", name: "muse spark 1.2" },
    { id: "meta/muse-spark-1.2-contributor", name: "muse spark 1.2 contributor" },
    { id: "meta/muse-spark-1.3", name: "muse spark 1.3" },
    { id: "meta/muse-spark-1.3-contributor", name: "muse spark 1.3 contributor" },
    { id: "nvidia/nemotron-3-nano-30b-a3b", name: "nemotron 3 nano 30b a3b" },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "nemotron 3 ultra" },
    { id: "nvidia/nemotron-3.5-lightning", name: "nemotron 3.5 lightning 30b" },
    { id: "amazon/nova-2-lite", name: "nova 2 lite" },
    { id: "amazon/nova-lite", name: "nova lite" },
    { id: "amazon/nova-micro", name: "nova micro" },
    { id: "amazon/nova-pro", name: "nova pro" },
    { id: "nvidia/nemotron-3-super-120b-a12b", name: "nvidia nemotron 3 super 120b a12b" },
    { id: "nvidia/nemotron-nano-12b-v2-vl", name: "nvidia nemotron nano 12b v2 vl" },
    { id: "nvidia/nemotron-nano-9b-v2", name: "nvidia nemotron nano 9b v2" },
    { id: "openai/o1", name: "o1" },
    { id: "openai/o3", name: "o3" },
    { id: "openai/o3-fast", name: "o3 (fast)" },
    { id: "openai/o3-pro", name: "o3 pro" },
    { id: "openai/o3-mini", name: "o3-mini" },
    { id: "openai/o4-mini", name: "o4-mini" },
    { id: "openai/o4-mini-fast", name: "o4-mini (fast)" },
    { id: "mistral/pixtral-12b", name: "pixtral 12b 2409" },
    { id: "alibaba/qwen-3-32b", name: "qwen 3 32b" },
    { id: "alibaba/qwen3-coder-30b-a3b", name: "qwen 3 coder 30b a3b instruct" },
    { id: "alibaba/qwen3-max-thinking", name: "qwen 3 max thinking" },
    { id: "alibaba/qwen3.5-flash", name: "qwen 3.5 flash" },
    { id: "alibaba/qwen3.5-plus", name: "qwen 3.5 plus" },
    { id: "alibaba/qwen3.6-27b", name: "qwen 3.6 27b" },
    { id: "alibaba/qwen-3.6-max-preview", name: "qwen 3.6 max preview" },
    { id: "alibaba/qwen3.6-plus", name: "qwen 3.6 plus" },
    { id: "alibaba/qwen3.7-flash", name: "qwen 3.7 flash" },
    { id: "alibaba/qwen3.7-max", name: "qwen 3.7 max" },
    { id: "alibaba/qwen3.7-plus", name: "qwen 3.7 plus" },
    { id: "alibaba/qwen3.8-flash", name: "qwen 3.8 flash" },
    { id: "alibaba/qwen3.8-flash-next", name: "qwen 3.8 flash next" },
    { id: "alibaba/qwen3.8-max", name: "qwen 3.8 max" },
    { id: "alibaba/qwen-3-235b", name: "qwen3 235b a22b" },
    { id: "alibaba/qwen3-coder", name: "qwen3 coder 480b a35b instruct" },
    { id: "alibaba/qwen3-coder-next", name: "qwen3 coder next" },
    { id: "alibaba/qwen3-coder-plus", name: "qwen3 coder plus" },
    { id: "alibaba/qwen3-max", name: "qwen3 max" },
    { id: "alibaba/qwen3-max-preview", name: "qwen3 max preview" },
    { id: "alibaba/qwen3-next-80b-a3b-instruct", name: "qwen3 next 80b a3b instruct" },
    { id: "alibaba/qwen3-next-80b-a3b-thinking", name: "qwen3 next 80b a3b thinking" },
    { id: "alibaba/qwen3-vl-235b-a22b-instruct", name: "qwen3 vl 235b a22b instruct" },
    { id: "alibaba/qwen3-vl-instruct", name: "qwen3 vl 235b a22b instruct" },
    { id: "alibaba/qwen3-235b-a22b-thinking", name: "qwen3 vl 235b a22b thinking" },
    { id: "alibaba/qwen3-vl-thinking", name: "qwen3 vl 235b a22b thinking" },
    { id: "alibaba/qwen-3-14b", name: "qwen3-14b" },
    { id: "alibaba/qwen-3-30b", name: "qwen3-30b-a3b" },
    { id: "alibaba/qwen3.8-2.4t-a95b", name: "qwen3.8 2.4t a95b" },
    { id: "alibaba/qwen3.8-27b", name: "qwen3.8 27b" },
    { id: "alibaba/qwen3.8-max-0902", name: "qwen3.8 max 0902" },
    { id: "sakana/namazu", name: "sakana namazu" },
    { id: "bytedance/seed-1.6", name: "seed 1.6" },
    { id: "stepfun/step-3.7-flash", name: "step 3.7 flash" },
    { id: "stepfun/step-3.5-flash", name: "stepfun 3.5 flash" },
    { id: "tencent/hy4-preview", name: "tencent hy4 preview" },
    { id: "arcee-ai/trinity-large-thinking", name: "trinity large thinking" },
  ] },
  { id: "xai", label: "xai", models: [
    { id: "grok-4.3", name: "grok 4.3" },
    { id: "grok-4.5", name: "grok 4.5" },
    { id: "grok-4.6", name: "grok 4.6" },
  ] },
  { id: "xiaomi", label: "xiaomi", models: [
    { id: "mimo-v2.5", name: "mimo-v2.5" },
    { id: "mimo-v2.5-pro", name: "mimo-v2.5-pro" },
    { id: "mimo-v2.5-pro-ultraspeed", name: "mimo-v2.5-pro-ultraspeed" },
  ] },
  { id: "xiaomi-token-plan-ams", label: "xiaomi-token-plan-ams", models: [
    { id: "mimo-v2.5", name: "mimo-v2.5" },
    { id: "mimo-v2.5-pro", name: "mimo-v2.5-pro" },
  ] },
  { id: "xiaomi-token-plan-cn", label: "xiaomi-token-plan-cn", models: [
    { id: "mimo-v2.5", name: "mimo-v2.5" },
    { id: "mimo-v2.5-pro", name: "mimo-v2.5-pro" },
  ] },
  { id: "xiaomi-token-plan-sgp", label: "xiaomi-token-plan-sgp", models: [
    { id: "mimo-v2.5", name: "mimo-v2.5" },
    { id: "mimo-v2.5-pro", name: "mimo-v2.5-pro" },
  ] },
  { id: "zai", label: "zai", models: [
    { id: "glm-4.7", name: "glm-4.7" },
    { id: "glm-5-turbo", name: "glm-5-turbo" },
    { id: "glm-5.2", name: "glm-5.2" },
    { id: "glm-5.2-highspeed", name: "glm-5.2 highspeed" },
    { id: "glm-5.3", name: "glm-5.3" },
    { id: "glm-5.3-highspeed", name: "glm-5.3 highspeed" },
    { id: "glm-5.3-flash", name: "glm-5.3-flash" },
  ] },
  { id: "zai-coding-cn", label: "zai-coding-cn", models: [
    { id: "glm-4.6v", name: "glm-4.6v" },
    { id: "glm-4.7", name: "glm-4.7" },
    { id: "glm-5-turbo", name: "glm-5-turbo" },
    { id: "glm-5.1", name: "glm-5.1" },
    { id: "glm-5.2", name: "glm-5.2" },
    { id: "glm-5.2-highspeed", name: "glm-5.2 highspeed" },
    { id: "glm-5.3", name: "glm-5.3" },
    { id: "glm-5.3-highspeed", name: "glm-5.3 highspeed" },
    { id: "glm-5.3-flash", name: "glm-5.3-flash" },
    { id: "glm-5v-turbo", name: "glm-5v-turbo" },
  ] },
]
