// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminCreateUserRequest = { username: string, password: string, 
/**
 * 留空则回落为用户名。
 */
display_name?: string, 
/**
 * 直接建成管理员（默认普通账户）。
 */
is_admin: boolean, };
