// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 管理后台：账户行（含内容统计）。
 */
export type AdminUserRow = { id: string, username: string, display_name: string, is_admin: boolean, must_change_password: boolean, created_at: string, last_login_at: string | null, saves: number, storybooks: number, active_sessions: number, 
/**
 * 就是当前请求者自己：前端据此禁用「删除」（后端也会拒）。
 */
is_self: boolean, };
