// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 发给模型的上下文里的一条消息（日志视图用；只保留可读正文，工具调用等折叠为文本）。
 */
export type AiCallMessage = { 
/**
 * system / user / assistant
 */
role: string, content: string, };
