// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 静态属性修正（同名取 max）。
 */
export type AttributeModifier = { attribute: string, value: bigint, };
