// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 判定种类（#3）：谁掷骰 / 是否掷骰 / 比较对象是什么。
 */
export type CheckKind = "attribute" | "attack" | "save" | "passive";
