// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckKind } from "./CheckKind";
import type { CheckMode } from "./CheckMode";

/**
 * 判定器声明（#12）：参数化配置，引擎不预设骰系；lua 为自定义判定脚本（归一化 total / margin）。
 */
export type CheckerDef = { 
/**
 * 骰子表达式 1d20 / 1d100 / 3d6；None = 无骰（由 AI 依属性叙事裁决）。
 */
dice?: string | null, mode?: CheckMode | null, 
/**
 * 属性 → 固定修正映射（键为维度 key）；命中则覆盖中心偏移公式。
 */
attribute_modifier?: { [key in string]: bigint } | null, 
/**
 * 中心偏移公式（默认 (v - 50) / 5）。v1 仅支持默认公式。
 */
modifier_formula?: string | null, 
/**
 * 成功度分档阈值（按差值），默认 [+10, 0, -10]。
 */
degree_thresholds?: Array<bigint> | null, 
/**
 * Lua 判定脚本源码（归一化输出 total / margin）。
 */
lua?: string | null, 
/**
 * 判定种类（#3）：缺省 attribute。
 */
kind?: CheckKind | null, 
/**
 * 被动判定的基数（缺省 10；D&D 被动察觉 = 10 + 加值）。
 */
passive_base?: bigint | null, };
