// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSaveRequest = { storybook_id: string, title: string | null, controlled_character_id: string | null, is_sandbox: boolean | null, };
