// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CondExpr } from "./CondExpr";
import type { ImmediateEffect } from "./ImmediateEffect";

/**
 * 条件触发（事件 + 条件 + 效果）。
 */
export type EffectTrigger = { id: string, event: string, condition?: CondExpr | null, effects: Array<ImmediateEffect>, };
