// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnemyView } from "./EnemyView";

/**
 * 结构化遭遇：导演创建，投影给前端与提示词。
 */
export type EncounterView = { id: string, name: string, enemies: Array<EnemyView>, note?: string | null, active: boolean, };
