// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 预置遭遇里的一条怪物模板引用（template_id 必须命中 kind = "monster" 的图鉴条目）。
 */
export type EncounterPresetEnemy = { template_id: string, 
/**
 * 展开数量（缺省 1）。
 */
count?: number | null, };
