// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 遭遇敌方单位的输入形态（hp 缺省由引擎给一个合理初始值）。
 */
export type EnemySpec = { name: string, hp: bigint | null, 
/**
 * 防御值（缺省 12：越高越难打中）
 */
ac: bigint | null, };
