// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 遭遇里的敌方单位（3a：只有名字与 HP；先攻/回合见后续）。
 */
export type EnemyView = { 
/**
 * 遭遇内寻址 id（e1、e2…）：玩家/引擎引用某个敌人时用它。
 */
id: string, name: string, hp: bigint, max: bigint, 
/**
 * 防御值：攻击判定的难度就是它（缺省 12）。
 */
ac: bigint, };
