// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 故事书实体的结构化引用（#23 ④ 精准指向）：creator 在结对里显式指定「要改这个」。
 * 单例 meta / world 无 id；声明区（flag/event/relationship_type/target_type）id = key；
 * 嵌套 scene / goal / trigger 带 parent_id。
 */
export type EntityRef = { kind: string, id: string | null, parent_id: string | null, name: string, };
