// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnemySpec } from "./EnemySpec";

export type IntentEnvelope = { 
/**
 * 意图幂等 id（#04 ⑨）：同一回合内重复的 id 只结算一次。
 * 缺省 = 旧协议 / 老模型没给 id，此时保持既有行为（不去重）。
 */
intent_id?: string | null, } & ({ "type": "think", content: string, } | { "type": "narrate", content: string, actor_id: string | null, } | { "type": "speak", content: string, tone: string | null, actor_id: string | null, } | { "type": "emote", content: string, emotion: string | null, actor_id: string | null, } | { "type": "move", destination_id: string, character_id: string | null, } | { "type": "use_skill", skill_id: string, target_id: string | null, } | { "type": "use_item", item_id: string, target_id: string | null, } | { "type": "interact", object_id: string, action: string, } | { "type": "check", attribute: string, difficulty: bigint | null, actor_id: string | null, 
/**
 * 对抗判定的对手（判定 C3）：角色实例（模板 id / 名字 / 实例键都能命中）或
 * 静态被动值的标识。给了对手 = 双方各掷一次比大小（对手命中不了实例时，
 * 用它的静态被动值）；判定器声明 mode = opposed 却不给对手 → 意图被驳回。
 */
opponent_id?: string | null, } | { "type": "query_world", query: string, } | { "type": "query_character", character_id: string | null, } | { "type": "query_relationships", entity_id: string | null, } | { "type": "advance_scene", target_scene_id: string | null, abandon: boolean, } | { "type": "intervene", content: string, } | { "type": "quest", text: string, hidden: boolean, primary: boolean, } | { "type": "adjust", character_id: string, resource: string, amount: bigint, } | { "type": "strike", enemy_id: string, skill_id: string | null, } | { "type": "enemy_strike", enemy_id: string, target_id: string | null, skill_id: string | null, } | { "type": "encounter", name: string, enemies: Array<EnemySpec>, note: string | null, } | { "type": "status", character_id: string, status_id: string, remove: boolean, } | { "type": "summary", text: string, } | { "type": "finish_turn" });
