// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRef } from "./EntityRef";

/**
 * 编辑器 C 范式结对会话的一条消息（#23 ④）。建议「待审查」不入此表——它是临时态，
 * 采纳后才经编辑操作落入草稿，避免刷新后重复采纳。
 */
export type PairMessageRecord = { seq: bigint, role: string, content: string, 
/**
 * 仅 assistant：思考流（reasoning_content）正文（可选）。
 */
reasoning?: string | null, model: string | null, is_error: boolean, tools: unknown, 
/**
 * 该消息显式引用的故事书实体（用户消息）。
 */
refs?: Array<EntityRef> | null, 
/**
 * 用户消息的附件（JSON 数组：name + 文本正文）。
 */
attachments?: unknown, };
