// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorRef } from "./ActorRef";

export type PendingPayload = { action_id: string, intent_id: string | null, actor: ActorRef, description: string, impact: string | null, timeout_ms: bigint, };
