// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 运行时任务（骨架目标 + 导演新增），投影给前端与提示词。
 */
export type QuestView = { id: string, text: string, done: boolean, 
/**
 * skeleton = 故事书骨架；gm = 导演运行时新增
 */
source: string, hidden: boolean, primary: boolean, };
