// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AI 思考链：某次 AI 调用（主线 / 角色）产出的 reasoning_content 纯文本。
 */
export type ReasoningPayload = { 
/**
 * 思考阶段：story_thinking / character_thinking（think 意图为 model_draft）
 */
stage: string, 
/**
 * 完整思考链文本。
 */
text: string, 
/**
 * 来源：provider = 供应商 reasoning_content；model = 模型写在正文里的 think 意图。
 * serde 缺省 provider，兼容 P3 之前的既有事件数据。
 */
source: string, };
