// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 技能 / 物品的资源消耗（#12 ②）。
 */
export type ResourceCost = { resource: string, amount: bigint, };
