// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRef } from "./EntityRef";
import type { RoundChannel } from "./RoundChannel";

export type RoundInput = { channel: RoundChannel, text: string, 
/**
 * 玩家在输入框里显式引用的故事书实体（随回合落进命令日志，供展示/重放）。
 */
refs?: Array<EntityRef>, };
