// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NarrativeOverride } from "./NarrativeOverride";

export type SaveSettings = { auto_confirm: boolean, 
/**
 * 本存档使用的模型；None = 用全局角色默认。
 */
model_provider_id?: string | null, model?: string | null, 
/**
 * 本存档的思考强度（reasoning_effort）；None = 用角色 / 供应商默认。
 */
reasoning_effort?: string | null, 
/**
 * 叙述段玩家偏好（section id → 开关 | 变体 key）；None = 全部用故事书默认。
 */
narrative?: { [key in string]: NarrativeOverride } | null, };
