// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScenePayload = { scene_id: string, title: string, description: string | null, present: Array<string>, };
