// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkeletonProgress = { goals: Record<string, unknown>, beats: Record<string, unknown>, abandoned_scenes: Array<string>, };
