// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusInstance = { id: string, name: string, turns_left: number | null, scenes_left: number | null, };
