// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImmediateEffect } from "./ImmediateEffect";
import type { StatusStack } from "./StatusStack";
import type { StatusUnit } from "./StatusUnit";

/**
 * 持续状态声明。
 */
export type StatusDef = { id: string, name: string, 
/**
 * 状态说明（可选，供编辑器与 AI 参考）。
 */
description?: string | null, duration: bigint, unit: StatusUnit, stack?: StatusStack | null, effect?: Array<ImmediateEffect> | null, };
