// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 故事书包里的故事书记录：草稿全文 + 已发布版次快照。
 * 与 `StorybookDocument` 的区别：这是**可移植的交付物**——导入方按它重建一条本地记录，
 * 因此不带本地并发令牌（`draft_version` 由导入方从 1 起算）。
 */
export type StorybookExportRecord = { id: string, title: string, revision: number, updated_at: string, released_at?: string | null, published: boolean, draft: unknown, released?: unknown, };
