// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorybookDocument = { id: string, revision: number, draft_version: number, updated_at: string, released_at: string | null, published: boolean, draft: unknown, released: unknown, };
