// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRef } from "./EntityRef";
import type { FocusEntity } from "./FocusEntity";
import type { RoundChannel } from "./RoundChannel";

export type SubmitRoundRequest = { channel: RoundChannel, text: string, request_id: string | null, 
/**
 * 引用的实体（轻量，随回合落库）。
 */
refs: Array<EntityRef> | null, 
/**
 * 引用的实体（完整定义，仅本轮请求透传给 AI，不落库）。
 */
focus: Array<FocusEntity> | null, };
