// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundChannel } from "./RoundChannel";

export type SubmitRoundRequest = { channel: RoundChannel, text: string, request_id: string | null, };
