// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemLevel } from "./SystemLevel";

export type SystemPayload = { level: SystemLevel, code: string | null, text: string, };
