// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpgradeReportGroup } from "./UpgradeReportGroup";

/**
 * 两段式升级的第一段产物：纯读、无副作用。
 */
export type UpgradeReport = { from_revision: number, to_revision: number, groups: UpgradeReportGroup, };
