// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * dry-run 报告里一个「新版故事书已删除」的人物：必须逐项裁决后才能升级。
 */
export type UpgradeGoneCharacter = { character_id: string, name: string, 
/**
 * 消失原因的提示（供 UI 展示）
 */
reason?: string | null, };
