// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveDetail } from "./SaveDetail";

/**
 * 执行升级结果：升级后的存档 + 自动备份包的磁盘文件名。
 */
export type UpgradeResult = { detail: SaveDetail, 
/**
 * 自动备份文件名（同数据目录 backups/）；幂等无操作时为空串。
 */
backup_name: string, };
