// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueSeverity } from "./IssueSeverity";

export type ValidationIssue = { severity: IssueSeverity, code: string, target: string | null, message: string, related_refs: Array<string> | null, };
