// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncounterView } from "./EncounterView";
import type { ProjectionMeta } from "./ProjectionMeta";
import type { QuestView } from "./QuestView";
import type { SkeletonProgress } from "./SkeletonProgress";

export type WorldProjection = { seq: bigint, scene_id: string, scene_title: string, characters: Record<string, unknown>, controlled: Array<string>, flags: Record<string, unknown>, progress: SkeletonProgress, 
/**
 * 运行时任务（骨架目标里带 text 的条目 + 导演新增），供 UI 与提示词使用。
 */
quests: Array<QuestView>, 
/**
 * 结构化遭遇（导演创建）。
 */
encounters: Array<EncounterView>, locations: Array<unknown>, meta: ProjectionMeta, };
