// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectionMeta } from "./ProjectionMeta";
import type { SkeletonProgress } from "./SkeletonProgress";

export type WorldProjection = { seq: bigint, scene_id: string, scene_title: string, characters: Record<string, unknown>, controlled: Array<string>, flags: Record<string, unknown>, progress: SkeletonProgress, locations: Array<unknown>, meta: ProjectionMeta, };
